autd3: autd3::Controller Class Reference
autd3::Controller Class Reference
AUTD Controller.
#include <controller.hpp>
Public Member Functions
Controller ()
core::Geometry & geometry () noexcept
Geometry of the devices.
const core::Geometry & geometry () const noexcept
Geometry of the devices.
bool open (core::LinkPtr link)
bool is_open () const noexcept
Verify the device is properly connected.
bool synchronize ()
Synchronize devices.
bool update_flag ()
Update flags (force fan and reads_fpga_info)
std::vector< driver::FPGAInfo > read_fpga_info ()
FPGA info.
bool clear ()
Clear all data in devices.
bool stop ()
Stop outputting.
bool close ()
Close the controller.
std::vector< driver::FirmwareInfo > firmware_infos ()
Enumerate firmware information.
template<typename H >
auto send (H &header) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H >, bool >
Send header data to devices.
template<typename H >
auto send (H &&header) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H >, bool >
Send header data to devices.
template<typename B >
auto send (B &body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramBody, B >, bool >
Send body data to devices.
template<typename B >
auto send (B &&body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramBody, B >, bool >
Send body data to devices.
template<typename H , typename B >
auto send (H &header, B &body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H > &&std::is_base_of_v< core::DatagramBody, B >, bool >
Send header and body data to devices.
template<typename H , typename B >
auto send (H &&header, B &&body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H > &&std::is_base_of_v< core::DatagramBody, B >, bool >
Send header and body data to devices.
Public Attributes
bool force_fan
If true, the fan will be forced to start.
bool reads_fpga_info
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
size_t check_trials
If > 0, this controller check ack from devices. This value represents the maximum number of trials for the check.
size_t send_interval
Transmission interval between frames when sending multiple data. The interval will be send_interval * driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC.
Detailed Description
AUTD Controller.
Definition at line 37 of file controller.hpp.
Constructor & Destructor Documentation
Controller()
autd3::Controller::Controller () inline
Definition at line 39 of file controller.hpp.
Member Function Documentation
clear()
bool autd3::Controller::clear () inline
Clear all data in devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 113 of file controller.hpp.
References autd3::driver::clear().
close()
bool autd3::Controller::close () inline
Close the controller.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 134 of file controller.hpp.
References autd3::driver::clear().
firmware_infos()
std::vector<driver::FirmwareInfo> autd3::Controller::firmware_infos () inline
Enumerate firmware information.
Returns
vector of driver::FirmwareInfo. If failed, the vector is empty.
Definition at line 145 of file controller.hpp.
References autd3::driver::cpu_version(), autd3::driver::fpga_functions(), and autd3::driver::fpga_version().
geometry() [1/2]
const core::Geometry& autd3::Controller::geometry () const inline noexcept
Geometry of the devices.
Definition at line 49 of file controller.hpp.
geometry() [2/2]
core::Geometry& autd3::Controller::geometry () inline noexcept
Geometry of the devices.
Definition at line 44 of file controller.hpp.
is_open()
bool autd3::Controller::is_open () const inline noexcept
Verify the device is properly connected.
Definition at line 63 of file controller.hpp.
Referenced by open().
open()
bool autd3::Controller::open (core::LinkPtr link) inline
Definition at line 51 of file controller.hpp.
References is_open(), and autd3::core::Geometry::num_devices().
read_fpga_info()
std::vector<driver::FPGAInfo> autd3::Controller::read_fpga_info () inline
FPGA info.
Returns
veetor of FPGAInfo. If failed, the vector is empty
Definition at line 101 of file controller.hpp.
send() [1/6]
template<typename B > auto autd3::Controller::send (B && body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramBody, B>, bool> inline
Send body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 208 of file controller.hpp.
send() [2/6]
template<typename B > auto autd3::Controller::send (B & body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramBody, B>, bool> inline
Send body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 198 of file controller.hpp.
send() [3/6]
template<typename H > auto autd3::Controller::send (H && header) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H>, bool> inline
Send header data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 189 of file controller.hpp.
send() [4/6]
template<typename H , typename B > auto autd3::Controller::send (H && header, B && body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H> && std::is_base_of_v<core::DatagramBody, B>, bool> inline
Send header and body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 243 of file controller.hpp.
send() [5/6]
template<typename H > auto autd3::Controller::send (H & header) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H>, bool> inline
Send header data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 179 of file controller.hpp.
send() [6/6]
template<typename H , typename B > auto autd3::Controller::send (H & header, B & body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H> && std::is_base_of_v<core::DatagramBody, B>, bool> inline
Send header and body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 217 of file controller.hpp.
References autd3::driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC, autd3::driver::force_fan(), and autd3::driver::reads_fpga_info().
stop()
bool autd3::Controller::stop () inline
Stop outputting.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 124 of file controller.hpp.
synchronize()
bool autd3::Controller::synchronize () inline
Synchronize devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 69 of file controller.hpp.
References autd3::core::Geometry::begin(), autd3::core::Geometry::end(), force_fan, autd3::driver::force_fan(), reads_fpga_info, and autd3::driver::reads_fpga_info().
update_flag()
bool autd3::Controller::update_flag () inline
Update flags (force fan and reads_fpga_info)
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 91 of file controller.hpp.
Member Data Documentation
check_trials
size_t autd3::Controller::check_trials
If > 0, this controller check ack from devices. This value represents the maximum number of trials for the check.
Definition at line 261 of file controller.hpp.
force_fan
bool autd3::Controller::force_fan
If true, the fan will be forced to start.
Definition at line 251 of file controller.hpp.
Referenced by synchronize().
reads_fpga_info
bool autd3::Controller::reads_fpga_info
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
Definition at line 256 of file controller.hpp.
Referenced by synchronize().
send_interval
size_t autd3::Controller::send_interval
Transmission interval between frames when sending multiple data. The interval will be send_interval * driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC.
Definition at line 267 of file controller.hpp.
The documentation for this class was generated from the following file:
include/autd3/controller.hpp