autd3: autd3::ControllerX< T, > Class Template Reference
autd3::ControllerX< T, > Class Template Reference
AUTD Controller.
#include <controller.hpp>
Public Member Functions
ControllerX ()
core::Geometry< T > & geometry () noexcept
Geometry of the devices.
const core::Geometry< T > & geometry () const noexcept
Geometry of the devices.
bool open (core::LinkPtr link)
bool is_open () const noexcept
Verify the device is properly connected.
bool synchronize ()
Synchronize devices.
bool update_flag ()
Update flags (force fan and reads_fpga_info)
std::vector< driver::FPGAInfo > read_fpga_info ()
FPGA info.
bool clear ()
Clear all data in devices.
bool stop ()
Stop outputting.
bool close ()
Close the controller.
std::vector< driver::FirmwareInfo > firmware_infos ()
Enumerate firmware information.
template<typename H >
auto send (H &header) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H >, bool >
Send header data to devices.
template<typename H >
auto send (H &&header) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H >, bool >
Send header data to devices.
template<typename B >
auto send (B &body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramBody< T >, B >, bool >
Send body data to devices.
template<typename B >
auto send (B &&body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramBody< T >, B >, bool >
Send body data to devices.
template<typename H , typename B >
auto send (H &header, B &body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H > &&std::is_base_of_v< core::DatagramBody< T >, B >, bool >
Send header and body data to devices.
template<typename H , typename B >
auto send (H &&header, B &&body) -> typename std::enable_if_t< std::is_base_of_v< core::DatagramHeader, H > &&std::is_base_of_v< core::DatagramBody< T >, B >, bool >
Send header and body data to devices.
bool stop ()
bool stop ()
bool stop ()
bool stop ()
Public Attributes
bool force_fan
If true, the fan will be forced to start.
bool reads_fpga_info
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
size_t check_trials
If > 0, this controller check ack from devices. This value represents the maximum number of trials for the check.
size_t send_interval
Transmission interval between frames when sending multiple data. The interval will be send_interval * driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC.
Detailed Description
template<typename T, std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr>
class autd3::ControllerX< T, >
AUTD Controller.
Definition at line 41 of file controller.hpp.
Constructor & Destructor Documentation
ControllerX()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::ControllerX< T, >::ControllerX () inline
Definition at line 43 of file controller.hpp.
Member Function Documentation
clear()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::clear () inline
Clear all data in devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 117 of file controller.hpp.
References autd3::driver::clear().
close()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::close () inline
Close the controller.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 134 of file controller.hpp.
References autd3::driver::clear().
firmware_infos()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<driver::FirmwareInfo> autd3::ControllerX< T, >::firmware_infos () inline
Enumerate firmware information.
Returns
vector of driver::FirmwareInfo. If failed, the vector is empty.
Definition at line 145 of file controller.hpp.
References autd3::driver::cpu_version(), autd3::driver::fpga_functions(), and autd3::driver::fpga_version().
geometry() [1/2]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> const core::Geometry<T>& autd3::ControllerX< T, >::geometry () const inline noexcept
Geometry of the devices.
Definition at line 53 of file controller.hpp.
geometry() [2/2]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> core::Geometry<T>& autd3::ControllerX< T, >::geometry () inline noexcept
Geometry of the devices.
Definition at line 48 of file controller.hpp.
is_open()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::is_open () const inline noexcept
Verify the device is properly connected.
Definition at line 67 of file controller.hpp.
Referenced by autd3::ControllerX< T, >::open().
open()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::open (core::LinkPtr link) inline
Definition at line 55 of file controller.hpp.
References autd3::ControllerX< T, >::is_open(), and autd3::core::Geometry< T, >::num_devices().
read_fpga_info()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<driver::FPGAInfo> autd3::ControllerX< T, >::read_fpga_info () inline
FPGA info.
Returns
veetor of FPGAInfo. If failed, the vector is empty
Definition at line 105 of file controller.hpp.
send() [1/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename B > auto autd3::ControllerX< T, >::send (B && body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramBody<T>, B>, bool> inline
Send body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 208 of file controller.hpp.
send() [2/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename B > auto autd3::ControllerX< T, >::send (B & body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramBody<T>, B>, bool> inline
Send body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 198 of file controller.hpp.
send() [3/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename H > auto autd3::ControllerX< T, >::send (H && header) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H>, bool> inline
Send header data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 189 of file controller.hpp.
send() [4/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename H , typename B > auto autd3::ControllerX< T, >::send (H && header, B && body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H> && std::is_base_of_v<core::DatagramBody<T>, B>, bool> inline
Send header and body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 243 of file controller.hpp.
send() [5/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename H > auto autd3::ControllerX< T, >::send (H & header) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H>, bool> inline
Send header data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 179 of file controller.hpp.
send() [6/6]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> template<typename H , typename B > auto autd3::ControllerX< T, >::send (H & header, B & body) -> typename std::enable_if_t<std::is_base_of_v<core::DatagramHeader, H> && std::is_base_of_v<core::DatagramBody<T>, B>, bool> inline
Send header and body data to devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 217 of file controller.hpp.
References autd3::driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC, autd3::driver::force_fan(), and autd3::driver::reads_fpga_info().
stop() [1/5]
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::stop ()
Stop outputting.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
stop() [2/5]
bool autd3::ControllerX< autd3::core::LegacyTransducer >::stop ()
Definition at line 293 of file controller.hpp.
stop() [3/5]
bool autd3::ControllerX< autd3::core::NormalTransducer >::stop ()
Definition at line 300 of file controller.hpp.
stop() [4/5]
bool autd3::ControllerX< autd3::core::NormalPhaseTransducer >::stop ()
Definition at line 307 of file controller.hpp.
stop() [5/5]
bool autd3::ControllerX< autd3::core::DynamicTransducer >::stop ()
Definition at line 314 of file controller.hpp.
References autd3::core::DynamicTransducer::mode().
synchronize()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::synchronize () inline
Synchronize devices.
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 73 of file controller.hpp.
References autd3::core::Geometry< T, >::begin(), autd3::core::Geometry< T, >::end(), autd3::ControllerX< T, >::force_fan, autd3::driver::force_fan(), autd3::ControllerX< T, >::reads_fpga_info, and autd3::driver::reads_fpga_info().
update_flag()
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::update_flag () inline
Update flags (force fan and reads_fpga_info)
Returns
if this function returns true and check_trials > 0, it guarantees that the devices have processed the data.
Definition at line 95 of file controller.hpp.
Member Data Documentation
check_trials
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::ControllerX< T, >::check_trials
If > 0, this controller check ack from devices. This value represents the maximum number of trials for the check.
Definition at line 261 of file controller.hpp.
force_fan
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::force_fan
If true, the fan will be forced to start.
Definition at line 251 of file controller.hpp.
Referenced by autd3::ControllerX< T, >::synchronize().
reads_fpga_info
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::ControllerX< T, >::reads_fpga_info
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
Definition at line 256 of file controller.hpp.
Referenced by autd3::ControllerX< T, >::synchronize().
send_interval
template<typename T , std::enable_if_t< std::is_base_of_v< core::Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::ControllerX< T, >::send_interval
Transmission interval between frames when sending multiple data. The interval will be send_interval * driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC.
Definition at line 267 of file controller.hpp.
The documentation for this class was generated from the following file:
include/autd3/controller.hpp