autd3: autd3::core::Amplitudes Class Reference
autd3::core::Amplitudes Class Reference final
Amplitude configuration for NormalPhaseMode.
#include <amplitudes.hpp>
Public Member Functions
Amplitudes (const double amp=1.0)
~Amplitudes () override=default
Amplitudes (const Amplitudes &v)=default
Amplitudes & operator= (const Amplitudes &obj)=default
Amplitudes (Amplitudes &&obj)=default
Amplitudes & operator= (Amplitudes &&obj)=default
void init () override
void pack (const Geometry &geometry, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Detailed Description
Amplitude configuration for NormalPhaseMode.
Definition at line 21 of file amplitudes.hpp.
Constructor & Destructor Documentation
Amplitudes() [1/3]
autd3::core::Amplitudes::Amplitudes (const double amp = 1.0) inline explicit
Definition at line 23 of file amplitudes.hpp.
~Amplitudes()
autd3::core::Amplitudes::~Amplitudes () override default
Amplitudes() [2/3]
autd3::core::Amplitudes::Amplitudes (const Amplitudes & v) default
Amplitudes() [3/3]
autd3::core::Amplitudes::Amplitudes (Amplitudes && obj) default
Member Function Documentation
init()
void autd3::core::Amplitudes::init () inline override virtual
Implements autd3::core::DatagramBody.
Definition at line 30 of file amplitudes.hpp.
is_finished()
bool autd3::core::Amplitudes::is_finished () const inline override virtual noexcept
Implements autd3::core::DatagramBody.
Definition at line 45 of file amplitudes.hpp.
Referenced by pack().
operator=() [1/2]
Amplitudes& autd3::core::Amplitudes::operator= (Amplitudes && obj) default
operator=() [2/2]
Amplitudes& autd3::core::Amplitudes::operator= (const Amplitudes & obj) default
pack()
void autd3::core::Amplitudes::pack (const Geometry & geometry, driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody.
Definition at line 32 of file amplitudes.hpp.
References autd3::core::Geometry::begin(), autd3::core::Geometry::end(), is_finished(), autd3::driver::normal_header(), and autd3::core::Geometry::num_transducers().
The documentation for this class was generated from the following file:
include/autd3/core/amplitudes.hpp