autd3: autd3::core::Modulation Class Reference
autd3::core::Modulation Class Reference abstract
Modulation controls the amplitude modulation.
#include <modulation.hpp>
Public Member Functions
Modulation ()=default
~Modulation () override=default
Modulation (const Modulation &v) noexcept=default
Modulation & operator= (const Modulation &obj)=default
Modulation (Modulation &&obj)=default
Modulation & operator= (Modulation &&obj)=default
virtual void calc ()=0
Calculate modulation data.
void build ()
Build modulation data.
void rebuild ()
Re-build modulation data.
const std::vector< uint8_t > & buffer () const noexcept
modulation data
uint32_t & sampling_frequency_division () noexcept
sampling frequency division ratio
size_t sampling_frequency_division () const noexcept
sampling frequency division ratio
double sampling_frequency () const noexcept
modulation sampling frequency
void init () override
void pack (const uint8_t msg_id, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Public Member Functions inherited from autd3::core::DatagramHeader
DatagramHeader ()=default
virtual ~DatagramHeader ()=default
DatagramHeader (const DatagramHeader &v)=default
DatagramHeader & operator= (const DatagramHeader &obj)=default
DatagramHeader (DatagramHeader &&obj)=default
DatagramHeader & operator= (DatagramHeader &&obj)=default
Detailed Description
Modulation controls the amplitude modulation.
Definition at line 35 of file modulation.hpp.
Constructor & Destructor Documentation
Modulation() [1/3]
autd3::core::Modulation::Modulation () default
~Modulation()
autd3::core::Modulation::~Modulation () override default
Modulation() [2/3]
autd3::core::Modulation::Modulation (const Modulation & v) default noexcept
Modulation() [3/3]
autd3::core::Modulation::Modulation (Modulation && obj) default
Member Function Documentation
buffer()
const std::vector<uint8_t>& autd3::core::Modulation::buffer () const inline noexcept
modulation data
Definition at line 71 of file modulation.hpp.
References autd3::core::ModProps::buffer.
Referenced by build(), is_finished(), and pack().
build()
void autd3::core::Modulation::build () inline
Build modulation data.
Definition at line 53 of file modulation.hpp.
References buffer(), autd3::core::ModProps::built, calc(), and autd3::driver::MOD_BUF_SIZE_MAX.
Referenced by init(), and rebuild().
calc()
virtual void autd3::core::Modulation::calc () pure virtual
Calculate modulation data.
Implemented in autd3::modulation::Sine, and autd3::modulation::Static.
Referenced by build().
init()
void autd3::core::Modulation::init () inline override virtual
Implements autd3::core::DatagramHeader.
Definition at line 93 of file modulation.hpp.
References build(), and autd3::core::ModProps::sent.
is_finished()
bool autd3::core::Modulation::is_finished () const inline override virtual noexcept
Implements autd3::core::DatagramHeader.
Definition at line 111 of file modulation.hpp.
References buffer(), and autd3::core::ModProps::sent.
Referenced by pack().
operator=() [1/2]
Modulation& autd3::core::Modulation::operator= (const Modulation & obj) default
operator=() [2/2]
Modulation& autd3::core::Modulation::operator= (Modulation && obj) default
pack()
void autd3::core::Modulation::pack (const uint8_t msg_id, driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramHeader.
Definition at line 98 of file modulation.hpp.
References autd3::core::ModProps::buffer, buffer(), autd3::core::ModProps::freq_div, is_finished(), autd3::driver::MOD_BODY_DATA_SIZE, autd3::driver::MOD_HEAD_DATA_SIZE, autd3::driver::modulation(), and autd3::core::ModProps::sent.
rebuild()
void autd3::core::Modulation::rebuild () inline
Re-build modulation data.
Definition at line 63 of file modulation.hpp.
References build(), and autd3::core::ModProps::built.
sampling_frequency()
double autd3::core::Modulation::sampling_frequency () const inline noexcept
modulation sampling frequency
Definition at line 89 of file modulation.hpp.
References autd3::driver::FPGA_CLK_FREQ, and autd3::core::ModProps::freq_div.
Referenced by autd3::modulation::Sine::calc().
sampling_frequency_division() [1/2]
size_t autd3::core::Modulation::sampling_frequency_division () const inline noexcept
sampling frequency division ratio
sampling frequency will be autd3::driver::FPGA_CLK_FREQ /(sampling frequency division ratio).
Definition at line 84 of file modulation.hpp.
References autd3::core::ModProps::freq_div.
sampling_frequency_division() [2/2]
uint32_t& autd3::core::Modulation::sampling_frequency_division () inline noexcept
sampling frequency division ratio
sampling frequency will be autd3::driver::FPGA_CLK_FREQ /(sampling frequency division ratio). The value must be larger than autd3::driver::MOD_SAMPLING_FREQ_DIV_MIN.
Definition at line 78 of file modulation.hpp.
References autd3::core::ModProps::freq_div.
The documentation for this class was generated from the following file:
include/autd3/core/modulation.hpp