autd3: autd3::driver Namespace Reference
autd3::driver Namespace Reference
driver namespace contains the logic to control the AUTD3 firmware and constans defined by hardware and firmware.
Classes
struct Body
class CPUControlFlags
struct Duty
struct FirmwareInfo
Firmware information.
class FPGAControlFlags
struct FPGAInfo
struct GainSTMBodyBody
struct GainSTMBodyHead
struct GlobalHeader
struct LegacyDrive
struct ModBody
struct ModHead
struct Phase
struct PointSTMBodyBody
struct PointSTMBodyHead
struct RxDatagram
struct RxMessage
struct SilencerHeader
struct STMFocus
struct SyncHeader
struct TxDatagram
Functions
void clear (TxDatagram &tx) noexcept
void sync (const uint8_t msg_id, const uint16_t sync_cycle_ticks, const uint16_t *const cycles, TxDatagram &tx) noexcept
void modulation (const uint8_t msg_id, const uint8_t *const mod_data, const size_t mod_size, const bool is_first_frame, const uint32_t freq_div, const bool is_last_frame, TxDatagram &tx) noexcept(false)
void config_silencer (const uint8_t msg_id, const uint16_t cycle, const uint16_t step, TxDatagram &tx)
void normal_legacy_header (const uint8_t msg_id, TxDatagram &tx) noexcept
void normal_legacy_body (const LegacyDrive *const drives, TxDatagram &tx) noexcept
void normal_header (const uint8_t msg_id, TxDatagram &tx) noexcept
void normal_duty_body (const Duty *drives, TxDatagram &tx) noexcept
void normal_phase_body (const Phase *drives, TxDatagram &tx) noexcept
void point_stm_header (const uint8_t msg_id, TxDatagram &tx) noexcept
void point_stm_body (const std::vector< std::vector< STMFocus >> &points, const bool is_first_frame, const uint32_t freq_div, const double sound_speed, const bool is_last_frame, TxDatagram &tx) noexcept(false)
void gain_stm_legacy_header (const uint8_t msg_id, TxDatagram &tx) noexcept
void gain_stm_legacy_body (const LegacyDrive *const drives, const bool is_first_frame, const uint32_t freq_div, const bool is_last_frame, TxDatagram &tx) noexcept(false)
void gain_stm_normal_header (const uint8_t msg_id, TxDatagram &tx) noexcept
void gain_stm_normal_phase (const Phase *const drives, const bool is_first_frame, const uint32_t freq_div, TxDatagram &tx) noexcept(false)
void gain_stm_normal_duty (const Duty *const drives, const bool is_last_frame, TxDatagram &tx) noexcept(false)
void force_fan (TxDatagram &tx, const bool value) noexcept
void reads_fpga_info (TxDatagram &tx, const bool value) noexcept
void cpu_version (TxDatagram &tx) noexcept
void fpga_version (TxDatagram &tx) noexcept
void fpga_functions (TxDatagram &tx) noexcept
std::ostream & operator<< (std::ostream &os, const FirmwareInfo &obj)
std::ostream & operator<< (std::ostream &os, const FPGAInfo &obj)
template<typename T >
auto is_missing_transducer (T x, T y) -> std::enable_if_t< std::is_integral_v< T >, bool >
Variables
constexpr uint8_t MSG_CLEAR = 0x00
constexpr uint8_t MSG_RD_CPU_VERSION = 0x01
constexpr uint8_t MSG_RD_FPGA_VERSION = 0x03
constexpr uint8_t MSG_RD_FPGA_FUNCTION = 0x04
constexpr uint8_t MSG_HEADER_ONLY_BEGINNING = 0x05
constexpr uint8_t MSG_HEADER_ONLY_END = 0x7F
constexpr uint8_t MSG_CONTAIN_BODY_BEGINNING = 0x80
constexpr uint8_t MSG_CONTAIN_BODY_END = 0xF0
constexpr uint8_t MSG_EMU_GEOMETRY_SET = 0xFF
constexpr size_t MOD_HEAD_DATA_SIZE = 120
constexpr size_t MOD_BODY_DATA_SIZE = 124
constexpr size_t POINT_STM_HEAD_DATA_SIZE = 61
constexpr size_t POINT_STM_BODY_DATA_SIZE = 62
constexpr size_t HEADER_SIZE = 128
constexpr size_t BODY_SIZE = 498
constexpr size_t EC_OUTPUT_FRAME_SIZE = HEADER_SIZE + BODY_SIZE
constexpr size_t EC_INPUT_FRAME_SIZE = 2
constexpr uint32_t EC_SYNC0_CYCLE_TIME_MICRO_SEC = 500
constexpr uint32_t EC_SYNC0_CYCLE_TIME_NANO_SEC = EC_SYNC0_CYCLE_TIME_MICRO_SEC * 1000
constexpr size_t EC_DEVICE_PER_FRAME = 2
constexpr size_t EC_FRAME_LENGTH = 14 + 2 + (10 + EC_OUTPUT_FRAME_SIZE + EC_INPUT_FRAME_SIZE + 2) * EC_DEVICE_PER_FRAME + 4
constexpr double EC_SPEED_BPS = 100.0 * 1000.0 * 1000.0
constexpr double EC_TRAFFIC_DELAY = EC_FRAME_LENGTH * 8.0 / EC_SPEED_BPS
constexpr uint8_t ENABLED_STM_BIT = 0x01
constexpr uint8_t ENABLED_MODULATOR_BIT = 0x02
constexpr uint8_t ENABLED_SILENCER_BIT = 0x04
constexpr size_t FPGA_CLK_FREQ = 163840000
constexpr uint16_t MAX_CYCLE = 8191
constexpr uint32_t MOD_SAMPLING_FREQ_DIV_MIN = 2320
constexpr size_t MOD_BUF_SIZE_MAX = 65536
constexpr double POINT_STM_FIXED_NUM_UNIT = 0.025
constexpr uint32_t STM_SAMPLING_FREQ_DIV_MIN = 3224
constexpr size_t POINT_STM_BUF_SIZE_MAX = 65536
constexpr size_t GAIN_STM_BUF_SIZE_MAX = 1024
constexpr uint16_t SILENCER_CYCLE_MIN = 2088
constexpr double pi = 3.141592653589793238462643383279502884L
constexpr size_t NUM_TRANS_IN_UNIT = 249
constexpr size_t NUM_TRANS_X = 18
constexpr size_t NUM_TRANS_Y = 14
constexpr double TRANS_SPACING_MM = 10.16
constexpr double DEVICE_WIDTH = 192.0
constexpr double DEVICE_HEIGHT = 151.4
Detailed Description
driver namespace contains the logic to control the AUTD3 firmware and constans defined by hardware and firmware.
Function Documentation
clear()
void autd3::driver::clear (TxDatagram & tx) inline noexcept
Definition at line 21 of file operation.hpp.
References MSG_CLEAR.
Referenced by autd3::Controller< T >::clear(), and autd3::Controller< T >::close().
config_silencer()
void autd3::driver::config_silencer (const uint8_t msg_id, const uint16_t cycle, const uint16_t step, TxDatagram & tx) inline
Definition at line 60 of file operation.hpp.
References autd3::driver::CPUControlFlags::CONFIG_SILENCER, autd3::driver::GlobalHeader::cpu_flag, autd3::driver::SilencerHeader::cycle, autd3::driver::CPUControlFlags::DO_SYNC, autd3::driver::TxDatagram::header(), autd3::driver::GlobalHeader::msg_id, autd3::driver::CPUControlFlags::remove(), autd3::driver::CPUControlFlags::set(), SILENCER_CYCLE_MIN, autd3::driver::GlobalHeader::silencer_header(), and autd3::driver::SilencerHeader::step.
Referenced by autd3::Controller< T >::config_silencer(), and autd3::Controller< T >::stop().
cpu_version()
void autd3::driver::cpu_version (TxDatagram & tx) inline noexcept
Definition at line 230 of file operation.hpp.
References autd3::driver::CPUControlFlags::MOD_END, and MSG_RD_CPU_VERSION.
Referenced by autd3::Controller< T >::firmware_infos().
force_fan()
void autd3::driver::force_fan (TxDatagram & tx, const bool value) inline noexcept
Definition at line 216 of file operation.hpp.
References autd3::driver::FPGAControlFlags::FORCE_FAN.
Referenced by autd3::Controller< T >::config_silencer(), autd3::Controller< T >::send(), autd3::Controller< T >::synchronize(), and autd3::Controller< T >::update_flag().
fpga_functions()
void autd3::driver::fpga_functions (TxDatagram & tx) inline noexcept
Definition at line 242 of file operation.hpp.
References autd3::driver::CPUControlFlags::MOD_BEGIN, MSG_RD_FPGA_FUNCTION, and autd3::driver::CPUControlFlags::STM_BEGIN.
Referenced by autd3::Controller< T >::firmware_infos().
fpga_version()
void autd3::driver::fpga_version (TxDatagram & tx) inline noexcept
Definition at line 236 of file operation.hpp.
References MSG_RD_FPGA_VERSION, and autd3::driver::CPUControlFlags::STM_BEGIN.
Referenced by autd3::Controller< T >::firmware_infos().
gain_stm_legacy_body()
void autd3::driver::gain_stm_legacy_body (const LegacyDrive *const drives, const bool is_first_frame, const uint32_t freq_div, const bool is_last_frame, TxDatagram & tx) inline noexcept
Definition at line 160 of file operation.hpp.
References autd3::driver::CPUControlFlags::STM_BEGIN, autd3::driver::CPUControlFlags::STM_END, and STM_SAMPLING_FREQ_DIV_MIN.
Referenced by autd3::core::GainSTM< LegacyTransducer >::pack().
gain_stm_legacy_header()
void autd3::driver::gain_stm_legacy_header (const uint8_t msg_id, TxDatagram & tx) inline noexcept
Definition at line 152 of file operation.hpp.
References autd3::driver::FPGAControlFlags::LEGACY_MODE, autd3::driver::FPGAControlFlags::STM_GAIN_MODE, and autd3::driver::FPGAControlFlags::STM_MODE.
Referenced by autd3::core::GainSTM< LegacyTransducer >::pack().
gain_stm_normal_duty()
void autd3::driver::gain_stm_normal_duty (const Duty *const drives, const bool is_last_frame, TxDatagram & tx) inline noexcept
Definition at line 207 of file operation.hpp.
References autd3::driver::CPUControlFlags::IS_DUTY, and autd3::driver::CPUControlFlags::STM_END.
Referenced by autd3::core::GainSTM< NormalTransducer >::pack().
gain_stm_normal_header()
void autd3::driver::gain_stm_normal_header (const uint8_t msg_id, TxDatagram & tx) inline noexcept
Definition at line 180 of file operation.hpp.
References autd3::driver::FPGAControlFlags::LEGACY_MODE, autd3::driver::FPGAControlFlags::STM_GAIN_MODE, and autd3::driver::FPGAControlFlags::STM_MODE.
Referenced by autd3::core::GainSTM< NormalTransducer >::pack().
gain_stm_normal_phase()
void autd3::driver::gain_stm_normal_phase (const Phase *const drives, const bool is_first_frame, const uint32_t freq_div, TxDatagram & tx) inline noexcept
Definition at line 188 of file operation.hpp.
References autd3::driver::CPUControlFlags::IS_DUTY, autd3::driver::CPUControlFlags::STM_BEGIN, and STM_SAMPLING_FREQ_DIV_MIN.
Referenced by autd3::core::GainSTM< NormalTransducer >::pack().
is_missing_transducer()
template<typename T > auto autd3::driver::is_missing_transducer (T x, T y) -> std::enable_if_t<std::is_integral_v<T>, bool>
Definition at line 26 of file hardware.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::Device().
modulation()
void autd3::driver::modulation (const uint8_t msg_id, const uint8_t *const mod_data, const size_t mod_size, const bool is_first_frame, const uint32_t freq_div, const bool is_last_frame, TxDatagram & tx) inline noexcept
Definition at line 36 of file operation.hpp.
References autd3::driver::CPUControlFlags::CONFIG_SILENCER, autd3::driver::CPUControlFlags::DO_SYNC, autd3::driver::CPUControlFlags::MOD_BEGIN, autd3::driver::CPUControlFlags::MOD_END, and MOD_SAMPLING_FREQ_DIV_MIN.
Referenced by autd3::core::Modulation::pack().
normal_duty_body()
void autd3::driver::normal_duty_body (const Duty * drives, TxDatagram & tx) inline noexcept
Definition at line 95 of file operation.hpp.
References autd3::driver::CPUControlFlags::IS_DUTY.
Referenced by autd3::core::NormalTransducer::pack_body().
normal_header()
void autd3::driver::normal_header (const uint8_t msg_id, TxDatagram & tx) inline noexcept
Definition at line 88 of file operation.hpp.
References autd3::driver::FPGAControlFlags::LEGACY_MODE, and autd3::driver::FPGAControlFlags::STM_MODE.
Referenced by autd3::core::NormalTransducer::pack_header().
normal_legacy_body()
void autd3::driver::normal_legacy_body (const LegacyDrive *const drives, TxDatagram & tx) inline noexcept
Definition at line 82 of file operation.hpp.
Referenced by autd3::core::LegacyTransducer::pack_body().
normal_legacy_header()
void autd3::driver::normal_legacy_header (const uint8_t msg_id, TxDatagram & tx) inline noexcept
Definition at line 75 of file operation.hpp.
References autd3::driver::FPGAControlFlags::LEGACY_MODE, and autd3::driver::FPGAControlFlags::STM_MODE.
Referenced by autd3::core::LegacyTransducer::pack_header().
normal_phase_body()
void autd3::driver::normal_phase_body (const Phase * drives, TxDatagram & tx) inline noexcept
Definition at line 103 of file operation.hpp.
References autd3::driver::CPUControlFlags::IS_DUTY.
Referenced by autd3::core::NormalTransducer::pack_body().
operator<<() [1/2]
std::ostream& autd3::driver::operator<< (std::ostream & os, const FirmwareInfo & obj) inline
Definition at line 87 of file firmware_version.hpp.
References autd3::driver::FirmwareInfo::to_string().
operator<<() [2/2]
std::ostream& autd3::driver::operator<< (std::ostream & os, const FPGAInfo & obj) inline
Definition at line 100 of file defined.hpp.
References autd3::driver::FPGAInfo::to_string().
point_stm_body()
void autd3::driver::point_stm_body (const std::vector< std::vector< STMFocus >> & points, const bool is_first_frame, const uint32_t freq_div, const double sound_speed, const bool is_last_frame, TxDatagram & tx) inline noexcept
Definition at line 118 of file operation.hpp.
References autd3::driver::CPUControlFlags::STM_BEGIN, autd3::driver::CPUControlFlags::STM_END, and STM_SAMPLING_FREQ_DIV_MIN.
point_stm_header()
void autd3::driver::point_stm_header (const uint8_t msg_id, TxDatagram & tx) inline noexcept
Definition at line 111 of file operation.hpp.
References autd3::driver::FPGAControlFlags::STM_GAIN_MODE, and autd3::driver::FPGAControlFlags::STM_MODE.
Referenced by autd3::core::PointSTM< T, >::pack().
reads_fpga_info()
void autd3::driver::reads_fpga_info (TxDatagram & tx, const bool value) inline noexcept
Definition at line 223 of file operation.hpp.
References autd3::driver::CPUControlFlags::READS_FPGA_INFO.
Referenced by autd3::Controller< T >::config_silencer(), autd3::Controller< T >::send(), autd3::Controller< T >::synchronize(), and autd3::Controller< T >::update_flag().
sync()
void autd3::driver::sync (const uint8_t msg_id, const uint16_t sync_cycle_ticks, const uint16_t *const cycles, TxDatagram & tx) inline noexcept
Definition at line 26 of file operation.hpp.
References autd3::driver::CPUControlFlags::DO_SYNC.
Variable Documentation
BODY_SIZE
constexpr size_t autd3::driver::BODY_SIZE = 498 constexpr
Definition at line 19 of file ec_config.hpp.
DEVICE_HEIGHT
constexpr double autd3::driver::DEVICE_HEIGHT = 151.4 constexpr
Definition at line 23 of file hardware.hpp.
DEVICE_WIDTH
constexpr double autd3::driver::DEVICE_WIDTH = 192.0 constexpr
Definition at line 22 of file hardware.hpp.
EC_DEVICE_PER_FRAME
constexpr size_t autd3::driver::EC_DEVICE_PER_FRAME = 2 constexpr
Definition at line 26 of file ec_config.hpp.
EC_FRAME_LENGTH
constexpr size_t autd3::driver::EC_FRAME_LENGTH = 14 + 2 + (10 + EC_OUTPUT_FRAME_SIZE + EC_INPUT_FRAME_SIZE + 2) * EC_DEVICE_PER_FRAME + 4 constexpr
Definition at line 27 of file ec_config.hpp.
EC_INPUT_FRAME_SIZE
constexpr size_t autd3::driver::EC_INPUT_FRAME_SIZE = 2 constexpr
Definition at line 21 of file ec_config.hpp.
EC_OUTPUT_FRAME_SIZE
constexpr size_t autd3::driver::EC_OUTPUT_FRAME_SIZE = HEADER_SIZE + BODY_SIZE constexpr
Definition at line 20 of file ec_config.hpp.
EC_SPEED_BPS
constexpr double autd3::driver::EC_SPEED_BPS = 100.0 * 1000.0 * 1000.0 constexpr
Definition at line 28 of file ec_config.hpp.
EC_SYNC0_CYCLE_TIME_MICRO_SEC
constexpr uint32_t autd3::driver::EC_SYNC0_CYCLE_TIME_MICRO_SEC = 500 constexpr
Definition at line 23 of file ec_config.hpp.
EC_SYNC0_CYCLE_TIME_NANO_SEC
constexpr uint32_t autd3::driver::EC_SYNC0_CYCLE_TIME_NANO_SEC = EC_SYNC0_CYCLE_TIME_MICRO_SEC * 1000 constexpr
Definition at line 24 of file ec_config.hpp.
EC_TRAFFIC_DELAY
constexpr double autd3::driver::EC_TRAFFIC_DELAY = EC_FRAME_LENGTH * 8.0 / EC_SPEED_BPS constexpr
Definition at line 29 of file ec_config.hpp.
ENABLED_MODULATOR_BIT
constexpr uint8_t autd3::driver::ENABLED_MODULATOR_BIT = 0x02 constexpr
Definition at line 21 of file firmware_version.hpp.
Referenced by autd3::driver::FirmwareInfo::modulator_enabled().
ENABLED_SILENCER_BIT
constexpr uint8_t autd3::driver::ENABLED_SILENCER_BIT = 0x04 constexpr
Definition at line 22 of file firmware_version.hpp.
Referenced by autd3::driver::FirmwareInfo::silencer_enabled().
ENABLED_STM_BIT
constexpr uint8_t autd3::driver::ENABLED_STM_BIT = 0x01 constexpr
Definition at line 20 of file firmware_version.hpp.
Referenced by autd3::driver::FirmwareInfo::stm_enabled().
FPGA_CLK_FREQ
constexpr size_t autd3::driver::FPGA_CLK_FREQ = 163840000 constexpr
Definition at line 20 of file defined.hpp.
Referenced by autd3::core::NormalTransducer::frequency(), autd3::core::STM::sampling_frequency(), autd3::core::Modulation::sampling_frequency(), autd3::core::STM::set_frequency(), and autd3::core::NormalTransducer::set_frequency().
GAIN_STM_BUF_SIZE_MAX
constexpr size_t autd3::driver::GAIN_STM_BUF_SIZE_MAX = 1024 constexpr
Definition at line 31 of file defined.hpp.
Referenced by autd3::core::GainSTM< LegacyTransducer >::add(), and autd3::core::GainSTM< NormalTransducer >::add().
HEADER_SIZE
constexpr size_t autd3::driver::HEADER_SIZE = 128 constexpr
Definition at line 18 of file ec_config.hpp.
MAX_CYCLE
constexpr uint16_t autd3::driver::MAX_CYCLE = 8191 constexpr
Definition at line 22 of file defined.hpp.
MOD_BODY_DATA_SIZE
constexpr size_t autd3::driver::MOD_BODY_DATA_SIZE = 124 constexpr
Definition at line 28 of file defined.hpp.
Referenced by autd3::core::Modulation::pack().
MOD_BUF_SIZE_MAX
constexpr size_t autd3::driver::MOD_BUF_SIZE_MAX = 65536 constexpr
Definition at line 25 of file defined.hpp.
Referenced by autd3::core::Modulation::build(), and autd3::modulation::SineLegacy::calc().
MOD_HEAD_DATA_SIZE
constexpr size_t autd3::driver::MOD_HEAD_DATA_SIZE = 120 constexpr
Definition at line 27 of file defined.hpp.
Referenced by autd3::core::Modulation::pack().
MOD_SAMPLING_FREQ_DIV_MIN
constexpr uint32_t autd3::driver::MOD_SAMPLING_FREQ_DIV_MIN = 2320 constexpr
Definition at line 24 of file defined.hpp.
Referenced by modulation().
MSG_CLEAR
constexpr uint8_t autd3::driver::MSG_CLEAR = 0x00 constexpr
Definition at line 17 of file defined.hpp.
Referenced by clear().
MSG_CONTAIN_BODY_BEGINNING
constexpr uint8_t autd3::driver::MSG_CONTAIN_BODY_BEGINNING = 0x80 constexpr
Definition at line 23 of file defined.hpp.
MSG_CONTAIN_BODY_END
constexpr uint8_t autd3::driver::MSG_CONTAIN_BODY_END = 0xF0 constexpr
Definition at line 24 of file defined.hpp.
MSG_EMU_GEOMETRY_SET
constexpr uint8_t autd3::driver::MSG_EMU_GEOMETRY_SET = 0xFF constexpr
Definition at line 25 of file defined.hpp.
MSG_HEADER_ONLY_BEGINNING
constexpr uint8_t autd3::driver::MSG_HEADER_ONLY_BEGINNING = 0x05 constexpr
Definition at line 21 of file defined.hpp.
MSG_HEADER_ONLY_END
constexpr uint8_t autd3::driver::MSG_HEADER_ONLY_END = 0x7F constexpr
Definition at line 22 of file defined.hpp.
MSG_RD_CPU_VERSION
constexpr uint8_t autd3::driver::MSG_RD_CPU_VERSION = 0x01 constexpr
Definition at line 18 of file defined.hpp.
Referenced by cpu_version().
MSG_RD_FPGA_FUNCTION
constexpr uint8_t autd3::driver::MSG_RD_FPGA_FUNCTION = 0x04 constexpr
Definition at line 20 of file defined.hpp.
Referenced by fpga_functions().
MSG_RD_FPGA_VERSION
constexpr uint8_t autd3::driver::MSG_RD_FPGA_VERSION = 0x03 constexpr
Definition at line 19 of file defined.hpp.
Referenced by fpga_version().
NUM_TRANS_IN_UNIT
constexpr size_t autd3::driver::NUM_TRANS_IN_UNIT = 249 constexpr
Definition at line 18 of file hardware.hpp.
Referenced by autd3::core::Gain< core::LegacyTransducer >::build(), autd3::core::LegacyDriveData< T >::copy_from(), autd3::core::NormalDriveData< T >::copy_from(), autd3::core::Device< autd3::core::LegacyTransducer >::Device(), autd3::gain::Grouped< T, >::Grouped(), and autd3::core::Geometry< autd3::core::LegacyTransducer >::num_transducers().
NUM_TRANS_X
constexpr size_t autd3::driver::NUM_TRANS_X = 18 constexpr
Definition at line 19 of file hardware.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::Device().
NUM_TRANS_Y
constexpr size_t autd3::driver::NUM_TRANS_Y = 14 constexpr
Definition at line 20 of file hardware.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::Device().
pi
constexpr double autd3::driver::pi = 3.141592653589793238462643383279502884L constexpr
Definition at line 16 of file hardware.hpp.
Referenced by autd3::modulation::Static::calc(), autd3::modulation::Sine::calc(), autd3::modulation::SineSquared::calc(), autd3::modulation::SineLegacy::calc(), autd3::modulation::Square::calc(), autd3::core::propagate(), autd3::core::LegacyDriveData< T >::set_drive(), autd3::core::NormalDriveData< T >::set_drive(), autd3::core::LegacyTransducer::wavenumber(), and autd3::core::NormalTransducer::wavenumber().
POINT_STM_BODY_DATA_SIZE
constexpr size_t autd3::driver::POINT_STM_BODY_DATA_SIZE = 62 constexpr
Definition at line 31 of file defined.hpp.
Referenced by autd3::core::PointSTM< T, >::pack().
POINT_STM_BUF_SIZE_MAX
constexpr size_t autd3::driver::POINT_STM_BUF_SIZE_MAX = 65536 constexpr
Definition at line 30 of file defined.hpp.
Referenced by autd3::core::PointSTM< T, >::add(), and autd3::core::PointSTM< T, >::push_back().
POINT_STM_FIXED_NUM_UNIT
constexpr double autd3::driver::POINT_STM_FIXED_NUM_UNIT = 0.025 constexpr
Definition at line 27 of file defined.hpp.
Referenced by autd3::driver::STMFocus::STMFocus().
POINT_STM_HEAD_DATA_SIZE
constexpr size_t autd3::driver::POINT_STM_HEAD_DATA_SIZE = 61 constexpr
Definition at line 30 of file defined.hpp.
Referenced by autd3::core::PointSTM< T, >::pack().
SILENCER_CYCLE_MIN
constexpr uint16_t autd3::driver::SILENCER_CYCLE_MIN = 2088 constexpr
Definition at line 33 of file defined.hpp.
Referenced by config_silencer().
STM_SAMPLING_FREQ_DIV_MIN
constexpr uint32_t autd3::driver::STM_SAMPLING_FREQ_DIV_MIN = 3224 constexpr
Definition at line 29 of file defined.hpp.
Referenced by gain_stm_legacy_body(), gain_stm_normal_phase(), point_stm_body(), and autd3::core::STM::set_frequency().
TRANS_SPACING_MM
constexpr double autd3::driver::TRANS_SPACING_MM = 10.16 constexpr
Definition at line 21 of file hardware.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::Device().