autd3: autd3::core Namespace Reference
autd3::core Namespace Reference
core namespace provides an abstraction of the basic functionality for manipulating AUTD3.
Classes
struct DatagramBody
DatagramBody is a data to be packed in the Body part of the driver::TxDatagram.
struct DatagramHeader
DatagramHeader is a data to be packed in the Header part of the driver::TxDatagram.
struct Device
Device contains an AUTD device geometry.
class Directivity
Utility class to calculate directivity of ultrasound transducer.
struct DriveData
Abstract container of duty ratio and phase.
struct DynamicDriveData
DriveData for DynamicTransducer.
struct DynamicTransducer
Transduce with variable frequency.
struct Gain
Gain controls the duty ratio and phase of each transducer in AUTD devices.
struct GainProps
Properties of Gain.
struct GainSTM
GainSTM provides a function to display Gain sequentially and periodically.
struct GainSTM< DynamicTransducer >
GainSTM for DynamicTransducer.
struct GainSTM< LegacyTransducer >
GainSTM for LegacyTransducer.
struct GainSTM< NormalTransducer >
GainSTM for NormalTransducer.
struct Geometry
Geometry of all devices.
struct LegacyDriveData
DriveData for LegacyTransducer.
struct LegacyTransducer
Transduce with 40kHz frequency.
class Link
Link is the interface to the AUTD device.
struct ModProps
Properties of Modulation.
class Modulation
Modulation controls the amplitude modulation.
struct NormalDriveData
DriveData for NormalTransducer.
struct NormalTransducer
Transduce with variable frequency.
struct NullBody
struct NullHeader
struct Point
Controll point and duty shift used in PointSTM.
struct PointSTM
PointSTM provides a function to display the focus sequentially and periodically.
struct STM
STM provide hardware Spatio-Temporal Modulation or Lateral Modulation function.
struct Transducer
Transduce contains a position and id, direction, frequency of a transducer.
Typedefs
using Vector3 = Eigen::Matrix< double, 3, 1 >
using Vector4 = Eigen::Matrix< double, 4, 1 >
using Matrix4X4 = Eigen::Matrix< double, 4, 4 >
using Quaternion = Eigen::Quaternion< double >
using LinkPtr = std::unique_ptr< Link >
Functions
template<typename T >
auto rem_euclid (T a, T b) noexcept -> std::enable_if_t< std::is_signed_v< T >, T >
std::complex< double > propagate (const core::Vector3 &source_pos, const core::Vector3 &source_dir, const double attenuation, const double wavenumber, const core::Vector3 &target)
Variables
constexpr double DIR_COEFFICIENT_A [] = {1.0, 1.0, 1.0, 0.891250938, 0.707945784, 0.501187234, 0.354813389, 0.251188643, 0.199526231}
constexpr double DIR_COEFFICIENT_B []
constexpr double DIR_COEFFICIENT_C []
constexpr double DIR_COEFFICIENT_D []
Detailed Description
core namespace provides an abstraction of the basic functionality for manipulating AUTD3.
Typedef Documentation
LinkPtr
using autd3::core::LinkPtr = typedef std::unique_ptr<Link>
Definition at line 70 of file link.hpp.
Matrix4X4
using autd3::core::Matrix4X4 = typedef Eigen::Matrix<double, 4, 4>
Definition at line 38 of file transducer.hpp.
Quaternion
using autd3::core::Quaternion = typedef Eigen::Quaternion<double>
Definition at line 39 of file transducer.hpp.
Vector3
using autd3::core::Vector3 = typedef Eigen::Matrix<double, 3, 1>
Definition at line 36 of file transducer.hpp.
Vector4
using autd3::core::Vector4 = typedef Eigen::Matrix<double, 4, 1>
Definition at line 37 of file transducer.hpp.
Function Documentation
propagate()
std::complex<double> autd3::core::propagate (const core::Vector3 & source_pos, const core::Vector3 & source_dir, const double attenuation, const double wavenumber, const core::Vector3 & target) inline
Definition at line 62 of file utils.hpp.
References autd3::driver::pi, and autd3::core::Directivity::t4010a1().
rem_euclid()
template<typename T > auto autd3::core::rem_euclid (T a, T b) -> std::enable_if_t<std::is_signed_v<T>, T> noexcept
Definition at line 56 of file utils.hpp.
Referenced by autd3::core::NormalDriveData< T >::set_drive(), and autd3::core::DynamicDriveData< T >::set_drive().
Variable Documentation
DIR_COEFFICIENT_A
constexpr double autd3::core::DIR_COEFFICIENT_A[] = {1.0, 1.0, 1.0, 0.891250938, 0.707945784, 0.501187234, 0.354813389, 0.251188643, 0.199526231} constexpr
Definition at line 23 of file utils.hpp.
Referenced by autd3::core::Directivity::t4010a1().
DIR_COEFFICIENT_B
constexpr double autd3::core::DIR_COEFFICIENT_B[] constexpr
Initial value:
= {
    0., 0., -0.00459648054721, -0.0155520765675, -0.0208114779827, -0.0182211227016, -0.0122437497109, -0.00780345575475, -0.00312857467007}
Definition at line 24 of file utils.hpp.
Referenced by autd3::core::Directivity::t4010a1().
DIR_COEFFICIENT_C
constexpr double autd3::core::DIR_COEFFICIENT_C[] constexpr
Initial value:
= {
    0., 0., -0.000787968093807, -0.000307591508224, -0.000218348633296, 0.00047738416141, 0.000120353137658, 0.000323676257958, 0.000143850511}
Definition at line 26 of file utils.hpp.
Referenced by autd3::core::Directivity::t4010a1().
DIR_COEFFICIENT_D
constexpr double autd3::core::DIR_COEFFICIENT_D[] constexpr
Initial value:
= {
    0., 0., 1.60125528528e-05, 2.9747624976e-06, 2.31910931569e-05, -1.1901034125e-05, 6.77743734332e-06, -5.99548024824e-06, -4.79372835035e-06}
Definition at line 28 of file utils.hpp.
Referenced by autd3::core::Directivity::t4010a1().