autd3: autd3::core::Amplitudes< NormalPhaseTransducer > Struct Reference
autd3::core::Amplitudes< NormalPhaseTransducer > Struct Reference final
Amplitude configuration for NormalPhaseTransducer.
#include <normal_phase_transducer.hpp>
Public Member Functions
Amplitudes (const Geometry< NormalPhaseTransducer > &geometry, const double amp=1.0)
~Amplitudes () override=default
Amplitudes (const Amplitudes &v)=default
Amplitudes & operator= (const Amplitudes &obj)=default
Amplitudes (Amplitudes &&obj)=default
Amplitudes & operator= (Amplitudes &&obj)=default
std::vector< driver::Duty > & duties ()
Getter function for the duty data of all transducers.
void init () override
void pack (const Geometry< NormalPhaseTransducer > &, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Public Member Functions inherited from autd3::core::DatagramBody< NormalPhaseTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual bool is_finished () const=0
Detailed Description
Amplitude configuration for NormalPhaseTransducer.
Definition at line 85 of file normal_phase_transducer.hpp.
Constructor & Destructor Documentation
Amplitudes() [1/3]
autd3::core::Amplitudes< NormalPhaseTransducer >::Amplitudes (const Geometry< NormalPhaseTransducer > & geometry, const double amp = 1.0) inline explicit
Definition at line 86 of file normal_phase_transducer.hpp.
References autd3::core::Geometry< T, >::num_transducers().
~Amplitudes()
autd3::core::Amplitudes< NormalPhaseTransducer >::~Amplitudes () override default
Amplitudes() [2/3]
autd3::core::Amplitudes< NormalPhaseTransducer >::Amplitudes (const Amplitudes< NormalPhaseTransducer > & v) default
Amplitudes() [3/3]
autd3::core::Amplitudes< NormalPhaseTransducer >::Amplitudes (Amplitudes< NormalPhaseTransducer > && obj) default
Member Function Documentation
duties()
std::vector<driver::Duty>& autd3::core::Amplitudes< NormalPhaseTransducer >::duties () inline
Getter function for the duty data of all transducers.
Definition at line 100 of file normal_phase_transducer.hpp.
init()
void autd3::core::Amplitudes< NormalPhaseTransducer >::init () inline override virtual
Implements autd3::core::DatagramBody< NormalPhaseTransducer >.
Definition at line 102 of file normal_phase_transducer.hpp.
is_finished()
bool autd3::core::Amplitudes< NormalPhaseTransducer >::is_finished () const inline override noexcept
Definition at line 111 of file normal_phase_transducer.hpp.
operator=() [1/2]
Amplitudes& autd3::core::Amplitudes< NormalPhaseTransducer >::operator= (Amplitudes< NormalPhaseTransducer > && obj) default
operator=() [2/2]
Amplitudes& autd3::core::Amplitudes< NormalPhaseTransducer >::operator= (const Amplitudes< NormalPhaseTransducer > & obj) default
pack()
void autd3::core::Amplitudes< NormalPhaseTransducer >::pack (const Geometry< NormalPhaseTransducer > & , driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody< NormalPhaseTransducer >.
Definition at line 104 of file normal_phase_transducer.hpp.
References autd3::driver::normal_duty_body(), and autd3::driver::normal_header().
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/normal_phase_transducer.hpp