autd3: autd3::driver::TxDatagram Struct Reference
autd3::driver::TxDatagram Struct Reference
#include <datagram.hpp>
Public Member Functions
TxDatagram (const size_t size)
~TxDatagram ()=default
TxDatagram (const TxDatagram &v) noexcept=delete
TxDatagram & operator= (const TxDatagram &obj)=delete
TxDatagram (TxDatagram &&obj)=default
TxDatagram & operator= (TxDatagram &&obj)=default
TxDatagram clone () const
size_t size () const noexcept
size_t effective_size () const noexcept
std::vector< uint8_t > & data () noexcept
const std::vector< uint8_t > & data () const noexcept
GlobalHeader & header () noexcept
GlobalHeader const & header () const noexcept
Body * bodies () noexcept
void clear () noexcept
Public Attributes
size_t num_bodies
Detailed Description
Definition at line 23 of file datagram.hpp.
Constructor & Destructor Documentation
TxDatagram() [1/3]
autd3::driver::TxDatagram::TxDatagram (const size_t size) inline explicit
Definition at line 26 of file datagram.hpp.
References size().
~TxDatagram()
autd3::driver::TxDatagram::~TxDatagram () default
TxDatagram() [2/3]
autd3::driver::TxDatagram::TxDatagram (const TxDatagram & v) delete noexcept
TxDatagram() [3/3]
autd3::driver::TxDatagram::TxDatagram (TxDatagram && obj) default
Member Function Documentation
bodies()
Body* autd3::driver::TxDatagram::bodies () inline noexcept
Definition at line 50 of file datagram.hpp.
clear()
void autd3::driver::TxDatagram::clear () inline noexcept
Definition at line 52 of file datagram.hpp.
References autd3::driver::GlobalHeader::clear(), header(), and num_bodies.
Referenced by autd3::Controller< T >::config_silencer(), and autd3::Controller< T >::synchronize().
clone()
TxDatagram autd3::driver::TxDatagram::clone () const inline
Definition at line 33 of file datagram.hpp.
data() [1/2]
const std::vector<uint8_t>& autd3::driver::TxDatagram::data () const inline noexcept
Definition at line 45 of file datagram.hpp.
data() [2/2]
std::vector<uint8_t>& autd3::driver::TxDatagram::data () inline noexcept
Definition at line 43 of file datagram.hpp.
effective_size()
size_t autd3::driver::TxDatagram::effective_size () const inline noexcept
Definition at line 41 of file datagram.hpp.
References num_bodies.
header() [1/2]
GlobalHeader const& autd3::driver::TxDatagram::header () const inline noexcept
Definition at line 48 of file datagram.hpp.
header() [2/2]
GlobalHeader& autd3::driver::TxDatagram::header () inline noexcept
Definition at line 47 of file datagram.hpp.
Referenced by clear(), and autd3::driver::config_silencer().
operator=() [1/2]
TxDatagram& autd3::driver::TxDatagram::operator= (const TxDatagram & obj) delete
operator=() [2/2]
TxDatagram& autd3::driver::TxDatagram::operator= (TxDatagram && obj) default
size()
size_t autd3::driver::TxDatagram::size () const inline noexcept
Definition at line 39 of file datagram.hpp.
Referenced by TxDatagram().
Member Data Documentation
num_bodies
size_t autd3::driver::TxDatagram::num_bodies
Definition at line 24 of file datagram.hpp.
Referenced by clear(), and effective_size().
The documentation for this struct was generated from the following file:
include/autd3/driver/cpu/datagram.hpp