autd3: autd3::core::Amplitudes< DynamicTransducer > Struct Reference
autd3::core::Amplitudes< DynamicTransducer > Struct Reference final
Amplitude configuration for DynamicTransducer.
#include <dynamic_transducer.hpp>
Public Member Functions
Amplitudes (const Geometry< DynamicTransducer > &geometry, const double amp=1.0)
~Amplitudes () override=default
Amplitudes (const Amplitudes &v)=default
Amplitudes & operator= (const Amplitudes &obj)=default
Amplitudes (Amplitudes &&obj)=default
Amplitudes & operator= (Amplitudes &&obj)=default
std::vector< driver::Duty > & duties ()
Getter function for the duty data of all transducers.
void init () override
void pack (const Geometry< DynamicTransducer > &, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Public Member Functions inherited from autd3::core::DatagramBody< DynamicTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual bool is_finished () const=0
Detailed Description
Amplitude configuration for DynamicTransducer.
Definition at line 164 of file dynamic_transducer.hpp.
Constructor & Destructor Documentation
Amplitudes() [1/3]
autd3::core::Amplitudes< DynamicTransducer >::Amplitudes (const Geometry< DynamicTransducer > & geometry, const double amp = 1.0) inline explicit
Definition at line 165 of file dynamic_transducer.hpp.
References autd3::core::Geometry< T, >::num_transducers().
~Amplitudes()
autd3::core::Amplitudes< DynamicTransducer >::~Amplitudes () override default
Amplitudes() [2/3]
autd3::core::Amplitudes< DynamicTransducer >::Amplitudes (const Amplitudes< DynamicTransducer > & v) default
Amplitudes() [3/3]
autd3::core::Amplitudes< DynamicTransducer >::Amplitudes (Amplitudes< DynamicTransducer > && obj) default
Member Function Documentation
duties()
std::vector<driver::Duty>& autd3::core::Amplitudes< DynamicTransducer >::duties () inline
Getter function for the duty data of all transducers.
Definition at line 179 of file dynamic_transducer.hpp.
init()
void autd3::core::Amplitudes< DynamicTransducer >::init () inline override virtual
Implements autd3::core::DatagramBody< DynamicTransducer >.
Definition at line 181 of file dynamic_transducer.hpp.
is_finished()
bool autd3::core::Amplitudes< DynamicTransducer >::is_finished () const inline override noexcept
Definition at line 190 of file dynamic_transducer.hpp.
operator=() [1/2]
Amplitudes& autd3::core::Amplitudes< DynamicTransducer >::operator= (Amplitudes< DynamicTransducer > && obj) default
operator=() [2/2]
Amplitudes& autd3::core::Amplitudes< DynamicTransducer >::operator= (const Amplitudes< DynamicTransducer > & obj) default
pack()
void autd3::core::Amplitudes< DynamicTransducer >::pack (const Geometry< DynamicTransducer > & , driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody< DynamicTransducer >.
Definition at line 183 of file dynamic_transducer.hpp.
References autd3::driver::normal_duty_body(), and autd3::driver::normal_header().
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/dynamic_transducer.hpp