autd3: autd3::core::Gain< T, > Struct Template Reference
autd3::core::Gain< T, > Struct Template Reference abstract
Gain controls the duty ratio and phase of each transducer in AUTD devices.
#include <gain.hpp>
Public Member Functions
Gain ()
~Gain () override=default
Gain (const Gain &v)=default
Gain & operator= (const Gain &obj)=default
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
virtual void calc (const Geometry< T > &geometry)=0
Calculate duty ratio and phase of each transducer.
void build (const Geometry< T > &geometry)
Initialize data and call calc().
void rebuild (const Geometry< T > &geometry)
Re-calculate duty ratio and phase of each transducer.
T::D & drives ()
Getter function for the data of duty ratio and phase of each transducers.
bool built ()
void init () override
void pack (uint8_t msg_id, const Geometry< T > &geometry, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Public Member Functions inherited from autd3::core::DatagramBody< T >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual bool is_finished () const=0
Detailed Description
template<typename T, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr>
struct autd3::core::Gain< T, >
Gain controls the duty ratio and phase of each transducer in AUTD devices.
Definition at line 44 of file gain.hpp.
Constructor & Destructor Documentation
Gain() [1/3]
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::Gain< T, >::Gain () inline
Definition at line 45 of file gain.hpp.
~Gain()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::Gain< T, >::~Gain () override default
Gain() [2/3]
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::Gain< T, >::Gain (const Gain< T, > & v) default
Gain() [3/3]
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::Gain< T, >::Gain (Gain< T, > && obj) default
Member Function Documentation
build()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::Gain< T, >::build (const Geometry< T > & geometry) inline
Initialize data and call calc().
Parameters
geometry Geometry
Definition at line 62 of file gain.hpp.
Referenced by autd3::core::Gain< core::LegacyTransducer >::pack(), and autd3::core::Gain< core::LegacyTransducer >::rebuild().
built()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::core::Gain< T, >::built () inline
Definition at line 83 of file gain.hpp.
calc()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> virtual void autd3::core::Gain< T, >::calc (const Geometry< T > & geometry) pure virtual
Calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Referenced by autd3::core::Gain< core::LegacyTransducer >::build().
drives()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> T::D& autd3::core::Gain< T, >::drives () inline
Getter function for the data of duty ratio and phase of each transducers.
Definition at line 81 of file gain.hpp.
init()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::Gain< T, >::init () inline override virtual
Implements autd3::core::DatagramBody< T >.
Definition at line 85 of file gain.hpp.
Referenced by autd3::gain::Grouped< T, >::Grouped().
is_finished()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::core::Gain< T, >::is_finished () const inline override noexcept
Definition at line 97 of file gain.hpp.
Referenced by autd3::core::Gain< core::LegacyTransducer >::pack().
operator=() [1/2]
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> Gain& autd3::core::Gain< T, >::operator= (const Gain< T, > & obj) default
operator=() [2/2]
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> Gain& autd3::core::Gain< T, >::operator= (Gain< T, > && obj) default
pack()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::Gain< T, >::pack (uint8_t msg_id, const Geometry< T > & geometry, driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody< T >.
Definition at line 90 of file gain.hpp.
rebuild()
template<typename T , std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::Gain< T, >::rebuild (const Geometry< T > & geometry) inline
Re-calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Definition at line 73 of file gain.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/gain.hpp