autd3: autd3::core::Transducer Struct Reference
autd3::core::Transducer Struct Reference
Transduce contains a position and id, direction, frequency of a transducer.
#include <transducer.hpp>
Public Member Functions
Transducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
virtual ~Transducer ()=default
Transducer (const Transducer &v) noexcept=default
Transducer & operator= (const Transducer &obj)=default
Transducer (Transducer &&obj)=default
Transducer & operator= (Transducer &&obj)=default
double align_phase_at (const double dist, const double sound_speed) const
const Vector3 & position () const noexcept
Position of the transducer.
size_t id () const noexcept
ID of the transducer.
const Vector3 & x_direction () const noexcept
x direction of the transducer
const Vector3 & y_direction () const noexcept
y direction of the transducer
const Vector3 & z_direction () const noexcept
z direction of the transducer
uint16_t mod_delay () const noexcept
modulation delay of the transducer
uint16_t & mod_delay () noexcept
modulation delay of the transducer
uint16_t cycle () const
Frequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
double frequency () const
Frequency of the transducer.
void set_cycle (const uint16_t cycle) noexcept
Set fFrequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
void set_frequency (const double freq) noexcept
Set fFrequency of the transducer.
double wavelength (double sound_speed) const
Wavelength of the ultrasound emitted from the transducer.
double wavenumber (double sound_speed) const
Wavenumber of the ultrasound emitted from the transducer.
Detailed Description
Transduce contains a position and id, direction, frequency of a transducer.
Definition at line 46 of file transducer.hpp.
Constructor & Destructor Documentation
Transducer() [1/3]
autd3::core::Transducer::Transducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) inline noexcept
Definition at line 47 of file transducer.hpp.
~Transducer()
virtual autd3::core::Transducer::~Transducer () virtual default
Transducer() [2/3]
autd3::core::Transducer::Transducer (const Transducer & v) default noexcept
Transducer() [3/3]
autd3::core::Transducer::Transducer (Transducer && obj) default
Member Function Documentation
align_phase_at()
double autd3::core::Transducer::align_phase_at (const double dist, const double sound_speed) const inline
Definition at line 61 of file transducer.hpp.
References wavelength().
cycle()
uint16_t autd3::core::Transducer::cycle () const inline
Frequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
Definition at line 94 of file transducer.hpp.
Referenced by set_cycle(), and set_frequency().
frequency()
double autd3::core::Transducer::frequency () const inline
Frequency of the transducer.
Definition at line 98 of file transducer.hpp.
References autd3::driver::FPGA_CLK_FREQ.
Referenced by wavelength(), and wavenumber().
id()
size_t autd3::core::Transducer::id () const inline noexcept
ID of the transducer.
Definition at line 70 of file transducer.hpp.
mod_delay() [1/2]
uint16_t autd3::core::Transducer::mod_delay () const inline noexcept
modulation delay of the transducer
Definition at line 86 of file transducer.hpp.
mod_delay() [2/2]
uint16_t& autd3::core::Transducer::mod_delay () inline noexcept
modulation delay of the transducer
Definition at line 90 of file transducer.hpp.
operator=() [1/2]
Transducer& autd3::core::Transducer::operator= (const Transducer & obj) default
operator=() [2/2]
Transducer& autd3::core::Transducer::operator= (Transducer && obj) default
position()
const Vector3& autd3::core::Transducer::position () const inline noexcept
Position of the transducer.
Definition at line 66 of file transducer.hpp.
Referenced by autd3::core::Geometry::Device::center().
set_cycle()
void autd3::core::Transducer::set_cycle (const uint16_t cycle) inline noexcept
Set fFrequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
This has no effect in LegacyMode.
Definition at line 104 of file transducer.hpp.
References cycle().
Referenced by set_frequency().
set_frequency()
void autd3::core::Transducer::set_frequency (const double freq) inline noexcept
Set fFrequency of the transducer.
This has no effect in LegacyMode.
Definition at line 110 of file transducer.hpp.
References cycle(), autd3::driver::FPGA_CLK_FREQ, and set_cycle().
wavelength()
double autd3::core::Transducer::wavelength (double sound_speed) const inline
Wavelength of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Definition at line 119 of file transducer.hpp.
References frequency().
Referenced by align_phase_at().
wavenumber()
double autd3::core::Transducer::wavenumber (double sound_speed) const inline
Wavenumber of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Definition at line 124 of file transducer.hpp.
References frequency(), and autd3::driver::pi.
x_direction()
const Vector3& autd3::core::Transducer::x_direction () const inline noexcept
x direction of the transducer
Definition at line 74 of file transducer.hpp.
y_direction()
const Vector3& autd3::core::Transducer::y_direction () const inline noexcept
y direction of the transducer
Definition at line 78 of file transducer.hpp.
z_direction()
const Vector3& autd3::core::Transducer::z_direction () const inline noexcept
z direction of the transducer
Definition at line 82 of file transducer.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/transducer.hpp