autd3: autd3::core::Geometry< T, > Struct Template Reference
autd3::core::Geometry< T, > Struct Template Reference
Geometry of all devices.
#include <geometry.hpp>
Public Member Functions
Geometry ()
size_t num_devices () const noexcept
Number of devices.
size_t num_transducers () const noexcept
Number of transducers.
Vector3 center () const
Center position of all connected devices.
size_t add_device (const Vector3 &position, const Vector3 &euler_angles)
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
size_t add_device (const Vector3 &position, const Quaternion &quaternion)
Same as add_device(const Vector3&, const Vector3&), but using quaternion rather than zyz euler angles.
std::vector< Device< T > >::const_iterator begin () const noexcept
std::vector< Device< T > >::const_iterator end () const noexcept
std::vector< Device< T > >::iterator begin () noexcept
std::vector< Device< T > >::iterator end () noexcept
Device< T > & operator[] (const size_t i)
const Device< T > & operator[] (const size_t i) const
Public Attributes
double attenuation
Attenuation coefficient in Np/mm.
double sound_speed
Speed of sound in m/s.
Detailed Description
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr>
struct autd3::core::Geometry< T, >
Geometry of all devices.
Definition at line 27 of file geometry.hpp.
Constructor & Destructor Documentation
Geometry()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::Geometry< T, >::Geometry () inline
Definition at line 28 of file geometry.hpp.
Member Function Documentation
add_device() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::core::Geometry< T, >::add_device (const Vector3 & position, const Quaternion & quaternion) inline
Same as add_device(const Vector3&, const Vector3&), but using quaternion rather than zyz euler angles.
Parameters
position Position of transducer #0, which is the one at the lower-left corner.
quaternion rotation quaternion of the device.
Returns
an id of added device
Definition at line 80 of file geometry.hpp.
add_device() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::core::Geometry< T, >::add_device (const Vector3 & position, const Vector3 & euler_angles) inline
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
Parameters
position Position of transducer #0, which is the one at the lower-left corner.
euler_angles ZYZ convention euler angle of the device
Returns
an id of added device
Definition at line 69 of file geometry.hpp.
Referenced by autd3::core::Geometry< autd3::core::LegacyTransducer >::add_device().
begin() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<Device<T> >::const_iterator autd3::core::Geometry< T, >::begin () const inline noexcept
Definition at line 86 of file geometry.hpp.
Referenced by autd3::gain::Null< T, >::calc(), autd3::gain::Focus< T, >::calc(), autd3::gain::BesselBeam< T, >::calc(), autd3::core::Geometry< autd3::core::LegacyTransducer >::center(), and autd3::core::PointSTM< T, >::pack().
begin() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<Device<T> >::iterator autd3::core::Geometry< T, >::begin () inline noexcept
Definition at line 88 of file geometry.hpp.
center()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> Vector3 autd3::core::Geometry< T, >::center () const inline
Center position of all connected devices.
Definition at line 53 of file geometry.hpp.
end() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<Device<T> >::const_iterator autd3::core::Geometry< T, >::end () const inline noexcept
Definition at line 87 of file geometry.hpp.
Referenced by autd3::gain::Null< T, >::calc(), autd3::gain::Focus< T, >::calc(), autd3::gain::BesselBeam< T, >::calc(), autd3::core::Geometry< autd3::core::LegacyTransducer >::center(), and autd3::core::PointSTM< T, >::pack().
end() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> std::vector<Device<T> >::iterator autd3::core::Geometry< T, >::end () inline noexcept
Definition at line 89 of file geometry.hpp.
num_devices()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::core::Geometry< T, >::num_devices () const inline noexcept
Number of devices.
Definition at line 43 of file geometry.hpp.
Referenced by autd3::core::Gain< core::LegacyTransducer >::build().
num_transducers()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::core::Geometry< T, >::num_transducers () const inline noexcept
Number of transducers.
Definition at line 48 of file geometry.hpp.
operator[]() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> Device<T>& autd3::core::Geometry< T, >::operator[] (const size_t i) inline
Definition at line 91 of file geometry.hpp.
operator[]() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> const Device<T>& autd3::core::Geometry< T, >::operator[] (const size_t i) const inline
Definition at line 92 of file geometry.hpp.
Member Data Documentation
attenuation
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> double autd3::core::Geometry< T, >::attenuation
Attenuation coefficient in Np/mm.
Definition at line 33 of file geometry.hpp.
sound_speed
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> double autd3::core::Geometry< T, >::sound_speed
Speed of sound in m/s.
Definition at line 38 of file geometry.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/geometry.hpp