autd3: autd3::driver::FirmwareInfo Struct Reference
autd3::driver::FirmwareInfo Struct Reference
Firmware information.
#include <firmware_version.hpp>
Public Member Functions
FirmwareInfo (const size_t idx, const uint8_t cpu_version_number, const uint8_t fpga_version_number, const uint8_t fpga_function_bits) noexcept
std::string cpu_version () const
Get cpu firmware version.
std::string fpga_version () const
Get fpga firmware version.
bool stm_enabled () const noexcept
bool modulator_enabled () const noexcept
bool silencer_enabled () const noexcept
bool modulation_delay_enabled () const noexcept
std::string to_string () const
Detailed Description
Firmware information.
Definition at line 28 of file firmware_version.hpp.
Constructor & Destructor Documentation
FirmwareInfo()
autd3::driver::FirmwareInfo::FirmwareInfo (const size_t idx, const uint8_t cpu_version_number, const uint8_t fpga_version_number, const uint8_t fpga_function_bits) inline noexcept
Definition at line 29 of file firmware_version.hpp.
Member Function Documentation
cpu_version()
std::string autd3::driver::FirmwareInfo::cpu_version () const inline
Get cpu firmware version.
Definition at line 35 of file firmware_version.hpp.
Referenced by to_string().
fpga_version()
std::string autd3::driver::FirmwareInfo::fpga_version () const inline
Get fpga firmware version.
Definition at line 39 of file firmware_version.hpp.
Referenced by to_string().
modulation_delay_enabled()
bool autd3::driver::FirmwareInfo::modulation_delay_enabled () const inline noexcept
Returns
true if the firmware supports Modulation delay function
Definition at line 57 of file firmware_version.hpp.
References autd3::driver::ENABLED_MOD_DELAY_BIT.
Referenced by to_string().
modulator_enabled()
bool autd3::driver::FirmwareInfo::modulator_enabled () const inline noexcept
Returns
true if the firmware supports Modulator function
Definition at line 48 of file firmware_version.hpp.
References autd3::driver::ENABLED_MODULATOR_BIT.
Referenced by to_string().
silencer_enabled()
bool autd3::driver::FirmwareInfo::silencer_enabled () const inline noexcept
Returns
true if the firmware supports Silencer function
Definition at line 52 of file firmware_version.hpp.
References autd3::driver::ENABLED_SILENCER_BIT.
Referenced by to_string().
stm_enabled()
bool autd3::driver::FirmwareInfo::stm_enabled () const inline noexcept
Returns
true if the firmware supports STM function
Definition at line 44 of file firmware_version.hpp.
References autd3::driver::ENABLED_STM_BIT.
Referenced by to_string().
to_string()
std::string autd3::driver::FirmwareInfo::to_string () const inline
Definition at line 59 of file firmware_version.hpp.
References cpu_version(), fpga_version(), modulation_delay_enabled(), modulator_enabled(), silencer_enabled(), and stm_enabled().
Referenced by autd3::driver::operator<<().
The documentation for this struct was generated from the following file:
include/autd3/driver/firmware_version.hpp