autd3: autd3::core::GainSTM< DynamicTransducer > Struct Reference
autd3::core::GainSTM< DynamicTransducer > Struct Reference final
GainSTM for DynamicTransducer.
#include <gain.hpp>
Public Member Functions
GainSTM (const Geometry< DynamicTransducer > &geometry)
template<typename G , std::enable_if_t< std::is_base_of_v< Gain< DynamicTransducer >, G >, nullptr_t > = nullptr>
void add (G &gain)
Add gain.
size_t size () const override
void init () override
void pack (const Geometry< DynamicTransducer > &, driver::TxDatagram &tx) override
bool is_finished () const override
Public Member Functions inherited from autd3::core::STM< DynamicTransducer >
STM () noexcept
STM (const STM &v)=default
STM (STM &&obj)=default
virtual ~STM ()=default
STM & operator= (const STM &obj)=default
STM & operator= (STM &&obj)=default
virtual size_t size () const=0
double set_frequency (const double freq)
Set frequency of the STM.
double frequency () const
double sampling_frequency () const noexcept
Sampling frequency.
uint32_t sampling_frequency_division () const noexcept
Sampling frequency division.
uint32_t & sampling_frequency_division () noexcept
Sampling frequency division.
Public Member Functions inherited from autd3::core::DatagramBody< DynamicTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual bool is_finished () const=0
Detailed Description
GainSTM for DynamicTransducer.
Definition at line 146 of file gain.hpp.
Constructor & Destructor Documentation
GainSTM()
autd3::core::GainSTM< DynamicTransducer >::GainSTM (const Geometry< DynamicTransducer > & geometry) inline explicit
Definition at line 147 of file gain.hpp.
Member Function Documentation
add()
template<typename G , std::enable_if_t< std::is_base_of_v< Gain< DynamicTransducer >, G >, nullptr_t > = nullptr> void autd3::core::GainSTM< DynamicTransducer >::add (G & gain) inline
Add gain.
Parameters
[in] gain gain
Definition at line 154 of file gain.hpp.
References autd3::driver::GAIN_STM_BUF_SIZE_MAX.
init()
void autd3::core::GainSTM< DynamicTransducer >::init () inline override virtual
Implements autd3::core::DatagramBody< DynamicTransducer >.
Definition at line 164 of file gain.hpp.
is_finished()
bool autd3::core::GainSTM< DynamicTransducer >::is_finished () const inline override
Definition at line 208 of file gain.hpp.
References autd3::core::DynamicTransducer::legacy_mode().
pack()
void autd3::core::GainSTM< DynamicTransducer >::pack (const Geometry< DynamicTransducer > & , driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody< DynamicTransducer >.
Definition at line 166 of file gain.hpp.
References autd3::driver::gain_stm_legacy_body(), autd3::driver::gain_stm_legacy_header(), autd3::driver::gain_stm_normal_duty(), autd3::driver::gain_stm_normal_header(), autd3::driver::gain_stm_normal_phase(), and autd3::core::DynamicTransducer::legacy_mode().
size()
size_t autd3::core::GainSTM< DynamicTransducer >::size () const inline override
Definition at line 162 of file gain.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/stm/gain.hpp