autd3: autd3::driver::LegacyDrive Struct Reference
autd3::driver::LegacyDrive Struct Reference
#include <defined.hpp>
Public Member Functions
void set (const Drive d)
Static Public Member Functions
static uint8_t to_phase (const Drive d)
static uint8_t to_duty (const Drive d)
Public Attributes
uint8_t phase
uint8_t duty
Detailed Description
Definition at line 87 of file defined.hpp.
Member Function Documentation
set()
void autd3::driver::LegacyDrive::set (const Drive d) inline
Definition at line 94 of file defined.hpp.
References duty, phase, to_duty(), and to_phase().
Referenced by autd3::driver::gain_stm_legacy_body(), and autd3::driver::normal_legacy_body().
to_duty()
static uint8_t autd3::driver::LegacyDrive::to_duty (const Drive d) inline static
Definition at line 92 of file defined.hpp.
References autd3::driver::Drive::amp, and autd3::driver::pi.
Referenced by set().
to_phase()
static uint8_t autd3::driver::LegacyDrive::to_phase (const Drive d) inline static
Definition at line 91 of file defined.hpp.
References autd3::driver::Drive::phase.
Referenced by set(), autd3::driver::LegacyPhaseFull::set(), and autd3::driver::LegacyPhaseHalf::set().
Member Data Documentation
duty
uint8_t autd3::driver::LegacyDrive::duty
Definition at line 89 of file defined.hpp.
Referenced by set().
phase
uint8_t autd3::driver::LegacyDrive::phase
Definition at line 88 of file defined.hpp.
Referenced by set().
The documentation for this struct was generated from the following file:
include/autd3/driver/fpga/defined.hpp