autd3: autd3::core::PointSTM< T, > Struct Template Reference
autd3::core::PointSTM< T, > Struct Template Reference final
PointSTM provides a function to display the focus sequentially and periodically.
#include <point.hpp>
Public Types
using value_type = Point
Public Member Functions
PointSTM ()
void add (const Vector3 &point, uint8_t duty_shift=0)
Add control point.
void push_back (const value_type &v)
size_t size () const override
void init () override
void pack (const Geometry< T > &geometry, driver::TxDatagram &tx) override
bool is_finished () const override
Public Member Functions inherited from autd3::core::STM< LegacyTransducer >
STM () noexcept
STM (const STM &v)=default
STM (STM &&obj)=default
virtual ~STM ()=default
STM & operator= (const STM &obj)=default
STM & operator= (STM &&obj)=default
virtual size_t size () const=0
double set_frequency (const double freq)
Set frequency of the STM.
double frequency () const
double sampling_frequency () const noexcept
Sampling frequency.
uint32_t sampling_frequency_division () const noexcept
Sampling frequency division.
uint32_t & sampling_frequency_division () noexcept
Sampling frequency division.
Public Member Functions inherited from autd3::core::DatagramBody< LegacyTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual void pack (const Geometry< LegacyTransducer > &geometry, driver::TxDatagram &tx)=0
virtual bool is_finished () const=0
Detailed Description
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr>
struct autd3::core::PointSTM< T, >
PointSTM provides a function to display the focus sequentially and periodically.
PointSTM uses a timer on the FPGA to ensure that the focus is precisely timed. PointSTM currently has the following three limitations.
The maximum number of control points is driver::POINT_STM_BUF_SIZE_MAX.
Only a single focus can be displayed at a certain moment.
Definition at line 61 of file point.hpp.
Member Typedef Documentation
value_type
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> using autd3::core::PointSTM< T, >::value_type = Point
Definition at line 62 of file point.hpp.
Constructor & Destructor Documentation
PointSTM()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::PointSTM< T, >::PointSTM () inline
Definition at line 64 of file point.hpp.
Member Function Documentation
add()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::PointSTM< T, >::add (const Vector3 & point, uint8_t duty_shift = 0) inline
Add control point.
Parameters
[in] point control point
[in] duty_shift duty shift. The duty ratio will be (50% >> duty_shift).
Definition at line 71 of file point.hpp.
References autd3::driver::POINT_STM_BUF_SIZE_MAX.
init()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::PointSTM< T, >::init () inline override virtual
Implements autd3::core::DatagramBody< LegacyTransducer >.
Definition at line 82 of file point.hpp.
is_finished()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::core::PointSTM< T, >::is_finished () const inline override
Definition at line 110 of file point.hpp.
Referenced by autd3::core::PointSTM< T, >::pack().
pack()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::PointSTM< T, >::pack (const Geometry< T > & geometry, driver::TxDatagram & tx) inline override
Definition at line 83 of file point.hpp.
References autd3::core::Geometry< T, >::begin(), autd3::core::Geometry< T, >::end(), autd3::core::PointSTM< T, >::is_finished(), autd3::driver::POINT_STM_BODY_DATA_SIZE, autd3::driver::POINT_STM_HEAD_DATA_SIZE, and autd3::driver::point_stm_header().
push_back()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::PointSTM< T, >::push_back (const value_type & v) inline
Definition at line 76 of file point.hpp.
References autd3::driver::POINT_STM_BUF_SIZE_MAX.
size()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> size_t autd3::core::PointSTM< T, >::size () const inline override
Definition at line 81 of file point.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/stm/point.hpp