autd3: autd3::SilencerConfig Struct Reference
autd3::SilencerConfig Struct Reference final
Silencer Configuration.
#include <silencer_config.hpp>
Public Member Functions
SilencerConfig () noexcept
SilencerConfig (const uint16_t step, const uint16_t cycle) noexcept
void init () override
void pack (const uint8_t msg_id, driver::TxDatagram &tx) override
bool is_finished () const override
Public Member Functions inherited from autd3::core::DatagramHeader
DatagramHeader ()=default
virtual ~DatagramHeader ()=default
DatagramHeader (const DatagramHeader &v)=default
DatagramHeader & operator= (const DatagramHeader &obj)=default
DatagramHeader (DatagramHeader &&obj)=default
DatagramHeader & operator= (DatagramHeader &&obj)=default
Static Public Member Functions
static SilencerConfig none () noexcept
Create SilencerConfig to disable Silencer.
Public Attributes
uint16_t step
Silencer update step.
uint16_t cycle
Silencer sampling frequency division ratio.
Detailed Description
Silencer Configuration.
Definition at line 23 of file silencer_config.hpp.
Constructor & Destructor Documentation
SilencerConfig() [1/2]
autd3::SilencerConfig::SilencerConfig () inline noexcept
Definition at line 24 of file silencer_config.hpp.
Referenced by none().
SilencerConfig() [2/2]
autd3::SilencerConfig::SilencerConfig (const uint16_t step, const uint16_t cycle) inline explicit noexcept
Definition at line 25 of file silencer_config.hpp.
Member Function Documentation
init()
void autd3::SilencerConfig::init () inline override virtual
Implements autd3::core::DatagramHeader.
Definition at line 43 of file silencer_config.hpp.
is_finished()
bool autd3::SilencerConfig::is_finished () const inline override virtual
Implements autd3::core::DatagramHeader.
Definition at line 53 of file silencer_config.hpp.
none()
static SilencerConfig autd3::SilencerConfig::none () inline static noexcept
Create SilencerConfig to disable Silencer.
Definition at line 30 of file silencer_config.hpp.
References SilencerConfig().
pack()
void autd3::SilencerConfig::pack (const uint8_t msg_id, driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramHeader.
Definition at line 45 of file silencer_config.hpp.
References autd3::driver::config_silencer(), cycle, autd3::driver::null_header(), and step.
Member Data Documentation
cycle
uint16_t autd3::SilencerConfig::cycle
Silencer sampling frequency division ratio.
The sampling frequency will be driver::FPGA_CLK_FREQ/cycle. The larger the cycle, the stronger the effect of noise reduction.
Definition at line 41 of file silencer_config.hpp.
Referenced by pack().
step
uint16_t autd3::SilencerConfig::step
Silencer update step.
The smaller the step, the stronger the effect of noise reduction.
Definition at line 36 of file silencer_config.hpp.
Referenced by pack().
The documentation for this struct was generated from the following file:
include/autd3/core/silencer_config.hpp