autd3: autd3::driver::Duty Struct Reference
autd3::driver::Duty Struct Reference
#include <defined.hpp>
Public Member Functions
void set (const Drive d)
Static Public Member Functions
static uint16_t to_duty (const Drive d)
Public Attributes
uint16_t duty
Detailed Description
Definition at line 111 of file defined.hpp.
Member Function Documentation
set()
void autd3::driver::Duty::set (const Drive d) inline
Definition at line 118 of file defined.hpp.
References duty, and to_duty().
Referenced by autd3::driver::gain_stm_normal_duty(), and autd3::driver::normal_duty_body().
to_duty()
static uint16_t autd3::driver::Duty::to_duty (const Drive d) inline static
Definition at line 114 of file defined.hpp.
References autd3::driver::Drive::amp, autd3::driver::Drive::cycle, and autd3::driver::pi.
Referenced by set().
Member Data Documentation
duty
uint16_t autd3::driver::Duty::duty
Definition at line 112 of file defined.hpp.
Referenced by set().
The documentation for this struct was generated from the following file:
include/autd3/driver/fpga/defined.hpp