autd3: autd3::core::GainSTM Struct Reference
autd3::core::GainSTM Struct Reference final
GainSTM provides a function to display Gain sequentially and periodically.
#include <gain.hpp>
Public Member Functions
GainSTM (const Geometry &geometry)
template<typename G , std::enable_if_t< std::is_base_of_v< Gain, G >, nullptr_t > = nullptr>
void add (G &gain)
Add gain.
driver::GainSTMMode & mode () noexcept
size_t size () const override
void init () override
void pack (const Geometry &geometry, driver::TxDatagram &tx) override
bool is_finished () const override
Public Member Functions inherited from autd3::core::STM
STM () noexcept
virtual ~STM ()=default
STM (const STM &v)=default
STM & operator= (const STM &obj)=default
STM (STM &&obj)=default
STM & operator= (STM &&obj)=default
double set_frequency (const double freq)
Set frequency of the STM.
double frequency () const
double sampling_frequency () const noexcept
Sampling frequency.
uint32_t sampling_frequency_division () const noexcept
Sampling frequency division.
uint32_t & sampling_frequency_division () noexcept
Sampling frequency division.
Public Member Functions inherited from autd3::core::DatagramBody
DatagramBody ()=default
virtual ~DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody (DatagramBody &&obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
Detailed Description
GainSTM provides a function to display Gain sequentially and periodically.
GainSTM uses a timer on the FPGA to ensure that Gain is precisely timed. GainSTM currently has the following three limitations.
The maximum number of gains is driver::GAIN_STM_BUF_SIZE_MAX.
Definition at line 31 of file gain.hpp.
Constructor & Destructor Documentation
GainSTM()
autd3::core::GainSTM::GainSTM (const Geometry & geometry) inline explicit
Definition at line 32 of file gain.hpp.
Member Function Documentation
add()
template<typename G , std::enable_if_t< std::is_base_of_v< Gain, G >, nullptr_t > = nullptr> void autd3::core::GainSTM::add (G & gain) inline
Add gain.
Parameters
[in] gain gain
Definition at line 39 of file gain.hpp.
References autd3::driver::GAIN_STM_BUF_SIZE_MAX.
init()
void autd3::core::GainSTM::init () inline override virtual
Implements autd3::core::DatagramBody.
Definition at line 51 of file gain.hpp.
is_finished()
bool autd3::core::GainSTM::is_finished () const inline override virtual
Implements autd3::core::DatagramBody.
Definition at line 61 of file gain.hpp.
Referenced by pack().
mode()
driver::GainSTMMode& autd3::core::GainSTM::mode () inline noexcept
Definition at line 47 of file gain.hpp.
pack()
void autd3::core::GainSTM::pack (const Geometry & geometry, driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody.
Definition at line 53 of file gain.hpp.
References is_finished(), and autd3::core::Geometry::mode().
size()
size_t autd3::core::GainSTM::size () const inline override virtual
Implements autd3::core::STM.
Definition at line 49 of file gain.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/stm/gain.hpp