autd3: autd3::core::GainSTM< NormalTransducer > Struct Reference
autd3::core::GainSTM< NormalTransducer > Struct Reference final
GainSTM for NormalTransducer.
#include <gain.hpp>
Public Member Functions
GainSTM (const Geometry< NormalTransducer > &geometry)
template<typename G , std::enable_if_t< std::is_base_of_v< Gain< NormalTransducer >, G >, nullptr_t > = nullptr>
void add (G &gain)
Add gain.
size_t size () const override
driver::Mode & mode () noexcept
void init () override
void pack (const Geometry< NormalTransducer > &, driver::TxDatagram &tx) override
bool is_finished () const override
Public Member Functions inherited from autd3::core::STM< NormalTransducer >
STM () noexcept
STM (const STM &v)=default
STM (STM &&obj)=default
virtual ~STM ()=default
STM & operator= (const STM &obj)=default
STM & operator= (STM &&obj)=default
virtual size_t size () const=0
double set_frequency (const double freq)
Set frequency of the STM.
double frequency () const
double sampling_frequency () const noexcept
Sampling frequency.
uint32_t sampling_frequency_division () const noexcept
Sampling frequency division.
uint32_t & sampling_frequency_division () noexcept
Sampling frequency division.
Public Member Functions inherited from autd3::core::DatagramBody< NormalTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual bool is_finished () const=0
Detailed Description
GainSTM for NormalTransducer.
Definition at line 118 of file gain.hpp.
Constructor & Destructor Documentation
GainSTM()
autd3::core::GainSTM< NormalTransducer >::GainSTM (const Geometry< NormalTransducer > & geometry) inline explicit
Definition at line 119 of file gain.hpp.
Member Function Documentation
add()
template<typename G , std::enable_if_t< std::is_base_of_v< Gain< NormalTransducer >, G >, nullptr_t > = nullptr> void autd3::core::GainSTM< NormalTransducer >::add (G & gain) inline
Add gain.
Parameters
[in] gain gain
Definition at line 127 of file gain.hpp.
References autd3::driver::GAIN_STM_BUF_SIZE_MAX.
init()
void autd3::core::GainSTM< NormalTransducer >::init () inline override virtual
Implements autd3::core::DatagramBody< NormalTransducer >.
Definition at line 139 of file gain.hpp.
is_finished()
bool autd3::core::GainSTM< NormalTransducer >::is_finished () const inline override
Definition at line 166 of file gain.hpp.
References autd3::driver::PhaseDutyFull.
mode()
driver::Mode& autd3::core::GainSTM< NormalTransducer >::mode () inline noexcept
Definition at line 137 of file gain.hpp.
pack()
void autd3::core::GainSTM< NormalTransducer >::pack (const Geometry< NormalTransducer > & , driver::TxDatagram & tx) inline override virtual
Implements autd3::core::DatagramBody< NormalTransducer >.
Definition at line 141 of file gain.hpp.
References autd3::driver::gain_stm_normal_duty(), autd3::driver::gain_stm_normal_header(), autd3::driver::gain_stm_normal_phase(), and autd3::driver::PhaseDutyFull.
size()
size_t autd3::core::GainSTM< NormalTransducer >::size () const inline override
Definition at line 135 of file gain.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/stm/gain.hpp