autd3: autd3::core::Geometry::Device Struct Reference
autd3::core::Geometry::Device Struct Reference
Device contains an AUTD device geometry.
#include <geometry.hpp>
Public Member Functions
Device (const size_t id, const Vector3 &position, const Quaternion &rotation)
Device ()=delete
~Device ()=default
Device (const Device &v) noexcept=default
Device & operator= (const Device &obj)=default
Device (Device &&obj)=default
Device & operator= (Device &&obj)=default
Vector3 center () const
Center position of this device.
Vector3 to_local_position (const Vector3 &global_position) const
Convert a global position to a local position.
std::vector< Transducer >::const_iterator begin () const noexcept
std::vector< Transducer >::const_iterator end () const noexcept
std::vector< Transducer >::iterator begin () noexcept
std::vector< Transducer >::iterator end () noexcept
const Transducer & operator[] (const size_t i) const
Transducer & operator[] (const size_t i)
Detailed Description
Device contains an AUTD device geometry.
Definition at line 30 of file geometry.hpp.
Constructor & Destructor Documentation
Device() [1/4]
autd3::core::Geometry::Device::Device (const size_t id, const Vector3 & position, const Quaternion & rotation) inline explicit
Definition at line 31 of file geometry.hpp.
References autd3::driver::is_missing_transducer(), autd3::driver::NUM_TRANS_IN_UNIT, autd3::driver::NUM_TRANS_X, autd3::driver::NUM_TRANS_Y, and autd3::driver::TRANS_SPACING_MM.
Device() [2/4]
autd3::core::Geometry::Device::Device () delete
~Device()
autd3::core::Geometry::Device::~Device () default
Device() [3/4]
autd3::core::Geometry::Device::Device (const Device & v) default noexcept
Device() [4/4]
autd3::core::Geometry::Device::Device (Device && obj) default
Member Function Documentation
begin() [1/2]
std::vector<Transducer>::const_iterator autd3::core::Geometry::Device::begin () const inline noexcept
Definition at line 79 of file geometry.hpp.
Referenced by center().
begin() [2/2]
std::vector<Transducer>::iterator autd3::core::Geometry::Device::begin () inline noexcept
Definition at line 81 of file geometry.hpp.
center()
Vector3 autd3::core::Geometry::Device::center () const inline
Center position of this device.
Definition at line 60 of file geometry.hpp.
References begin(), end(), and autd3::core::Transducer::position().
Referenced by autd3::core::Geometry::center().
end() [1/2]
std::vector<Transducer>::const_iterator autd3::core::Geometry::Device::end () const inline noexcept
Definition at line 80 of file geometry.hpp.
Referenced by center().
end() [2/2]
std::vector<Transducer>::iterator autd3::core::Geometry::Device::end () inline noexcept
Definition at line 82 of file geometry.hpp.
operator=() [1/2]
Device& autd3::core::Geometry::Device::operator= (const Device & obj) default
operator=() [2/2]
Device& autd3::core::Geometry::Device::operator= (Device && obj) default
operator[]() [1/2]
Transducer& autd3::core::Geometry::Device::operator[] (const size_t i) inline
Definition at line 85 of file geometry.hpp.
operator[]() [2/2]
const Transducer& autd3::core::Geometry::Device::operator[] (const size_t i) const inline
Definition at line 84 of file geometry.hpp.
to_local_position()
Vector3 autd3::core::Geometry::Device::to_local_position (const Vector3 & global_position) const inline
Convert a global position to a local position.
Definition at line 73 of file geometry.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry.hpp