autd3: autd3::core::NormalTransducer Struct Reference
autd3::core::NormalTransducer Struct Reference final
Transduce with variable frequency.
#include <normal_transducer.hpp>
Public Member Functions
NormalTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
~NormalTransducer () override=default
NormalTransducer (const NormalTransducer &v) noexcept=default
NormalTransducer & operator= (const NormalTransducer &obj)=default
NormalTransducer (NormalTransducer &&obj)=default
NormalTransducer & operator= (NormalTransducer &&obj)=default
uint16_t cycle () const noexcept override
double frequency () const noexcept override
double wavelength (const double sound_speed) const noexcept override
Wavelength of the ultrasound emitted from the transducer.
double wavenumber (const double sound_speed) const noexcept override
Wavenumber of the ultrasound emitted from the transducer.
void set_cycle (const uint16_t cycle) noexcept
void set_frequency (const double freq) noexcept
Public Member Functions inherited from autd3::core::Transducer< NormalDriveData< NormalTransducer > >
Transducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
Transducer (const Transducer &v) noexcept=default
Transducer (Transducer &&obj)=default
virtual ~Transducer ()=default
Transducer & operator= (const Transducer &obj)=default
Transducer & operator= (Transducer &&obj)=default
double align_phase_at (const double dist, const double sound_speed) const
const Vector3 & position () const noexcept
Position of the transducer.
size_t id () const noexcept
ID of the transducer.
const Vector3 & x_direction () const noexcept
x direction of the transducer
const Vector3 & y_direction () const noexcept
y direction of the transducer
const Vector3 & z_direction () const noexcept
z direction of the transducer
uint16_t mod_delay () const noexcept
modulation delay of the transducer
uint16_t & mod_delay () noexcept
modulation delay of the transducer
virtual uint16_t cycle () const=0
Frequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
virtual double frequency () const=0
Frequency of the transducer.
Static Public Member Functions
static void pack_header (driver::TxDatagram &tx) noexcept
static void pack_body (bool &phase_sent, bool &duty_sent, const D &drives, driver::TxDatagram &tx) noexcept
Additional Inherited Members
Public Types inherited from autd3::core::Transducer< NormalDriveData< NormalTransducer > >
using D = NormalDriveData< NormalTransducer >
Detailed Description
Transduce with variable frequency.
Definition at line 54 of file normal_transducer.hpp.
Constructor & Destructor Documentation
NormalTransducer() [1/3]
autd3::core::NormalTransducer::NormalTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) inline noexcept
Definition at line 55 of file normal_transducer.hpp.
~NormalTransducer()
autd3::core::NormalTransducer::~NormalTransducer () override default
NormalTransducer() [2/3]
autd3::core::NormalTransducer::NormalTransducer (const NormalTransducer & v) default noexcept
NormalTransducer() [3/3]
autd3::core::NormalTransducer::NormalTransducer (NormalTransducer && obj) default
Member Function Documentation
cycle()
uint16_t autd3::core::NormalTransducer::cycle () const inline override noexcept
Definition at line 63 of file normal_transducer.hpp.
Referenced by set_cycle(), and set_frequency().
frequency()
double autd3::core::NormalTransducer::frequency () const inline override noexcept
Definition at line 64 of file normal_transducer.hpp.
References autd3::driver::FPGA_CLK_FREQ.
Referenced by wavelength(), and wavenumber().
operator=() [1/2]
NormalTransducer& autd3::core::NormalTransducer::operator= (const NormalTransducer & obj) default
operator=() [2/2]
NormalTransducer& autd3::core::NormalTransducer::operator= (NormalTransducer && obj) default
pack_body()
static void autd3::core::NormalTransducer::pack_body (bool & phase_sent, bool & duty_sent, const D & drives, driver::TxDatagram & tx) inline static noexcept
Definition at line 70 of file normal_transducer.hpp.
References autd3::driver::normal_duty_body(), and autd3::driver::normal_phase_body().
pack_header()
static void autd3::core::NormalTransducer::pack_header (driver::TxDatagram & tx) inline static noexcept
Definition at line 68 of file normal_transducer.hpp.
References autd3::driver::normal_header().
set_cycle()
void autd3::core::NormalTransducer::set_cycle (const uint16_t cycle) inline noexcept
Definition at line 80 of file normal_transducer.hpp.
References cycle().
Referenced by set_frequency().
set_frequency()
void autd3::core::NormalTransducer::set_frequency (const double freq) inline noexcept
Definition at line 82 of file normal_transducer.hpp.
References cycle(), autd3::driver::FPGA_CLK_FREQ, and set_cycle().
wavelength()
double autd3::core::NormalTransducer::wavelength (const double sound_speed) const inline override virtual noexcept
Wavelength of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< NormalDriveData< NormalTransducer > >.
Definition at line 65 of file normal_transducer.hpp.
References frequency().
wavenumber()
double autd3::core::NormalTransducer::wavenumber (const double sound_speed) const inline override virtual noexcept
Wavenumber of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< NormalDriveData< NormalTransducer > >.
Definition at line 66 of file normal_transducer.hpp.
References frequency(), and autd3::driver::pi.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/normal_transducer.hpp