autd3: autd3::core::STM< T, > Struct Template Reference
autd3::core::STM< T, > Struct Template Reference abstract
STM provide hardware Spatio-Temporal Modulation or Lateral Modulation function.
#include <stm.hpp>
Public Member Functions
STM () noexcept
virtual ~STM ()=default
STM (const STM &v)=default
STM & operator= (const STM &obj)=default
STM (STM &&obj)=default
STM & operator= (STM &&obj)=default
virtual size_t size () const =0
double set_frequency (const double freq)
Set frequency of the STM.
double frequency () const
double sampling_frequency () const noexcept
Sampling frequency.
uint32_t sampling_frequency_division () const noexcept
Sampling frequency division.
uint32_t & sampling_frequency_division () noexcept
Sampling frequency division.
Public Member Functions inherited from autd3::core::DatagramBody< LegacyTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual void init ()=0
virtual void pack (const Geometry< LegacyTransducer > &geometry, driver::TxDatagram &tx)=0
virtual bool is_finished () const=0
Detailed Description
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr>
struct autd3::core::STM< T, >
STM provide hardware Spatio-Temporal Modulation or Lateral Modulation function.
Definition at line 26 of file stm.hpp.
Constructor & Destructor Documentation
STM() [1/3]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::STM< T, >::STM () inline noexcept
Definition at line 27 of file stm.hpp.
~STM()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> virtual autd3::core::STM< T, >::~STM () virtual default
STM() [2/3]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::STM< T, >::STM (const STM< T, > & v) default
STM() [3/3]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::STM< T, >::STM (STM< T, > && obj) default
Member Function Documentation
frequency()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> double autd3::core::STM< T, >::frequency () const inline
Returns
frequency of STM
Definition at line 53 of file stm.hpp.
Referenced by autd3::core::STM< DynamicTransducer >::set_frequency().
operator=() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> STM& autd3::core::STM< T, >::operator= (const STM< T, > & obj) default
operator=() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> STM& autd3::core::STM< T, >::operator= (STM< T, > && obj) default
sampling_frequency()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> double autd3::core::STM< T, >::sampling_frequency () const inline noexcept
Sampling frequency.
Sampling frequency is driver::FPGA_CLK_FREQ/sampling_frequency_division()
Definition at line 59 of file stm.hpp.
Referenced by autd3::core::STM< DynamicTransducer >::frequency().
sampling_frequency_division() [1/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> uint32_t autd3::core::STM< T, >::sampling_frequency_division () const inline noexcept
Sampling frequency division.
Definition at line 64 of file stm.hpp.
sampling_frequency_division() [2/2]
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> uint32_t& autd3::core::STM< T, >::sampling_frequency_division () inline noexcept
Sampling frequency division.
The value must be larget than driver::STM_SAMPLING_FREQ_DIV_MIN.
Definition at line 70 of file stm.hpp.
set_frequency()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> double autd3::core::STM< T, >::set_frequency (const double freq) inline
Set frequency of the STM.
Parameters
[in] freq Frequency of the STM
STM mode has some constraints, which determine the actual frequency of the STM.
Returns
double Actual frequency of STM
Definition at line 42 of file stm.hpp.
size()
template<typename T = LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> virtual size_t autd3::core::STM< T, >::size () const pure virtual
Referenced by autd3::core::STM< DynamicTransducer >::frequency(), and autd3::core::STM< DynamicTransducer >::set_frequency().
The documentation for this struct was generated from the following file:
include/autd3/core/stm/stm.hpp