autd3: autd3::driver::Phase Struct Reference
autd3::driver::Phase Struct Reference
#include <defined.hpp>
Public Member Functions
void set (const Drive d)
Static Public Member Functions
static uint16_t to_phase (const Drive d)
Public Attributes
uint16_t phase
Detailed Description
Definition at line 100 of file defined.hpp.
Member Function Documentation
set()
void autd3::driver::Phase::set (const Drive d) inline
Definition at line 108 of file defined.hpp.
References phase, and to_phase().
Referenced by autd3::driver::gain_stm_normal_phase(), and autd3::driver::normal_phase_body().
to_phase()
static uint16_t autd3::driver::Phase::to_phase (const Drive d) inline static
Definition at line 103 of file defined.hpp.
References autd3::driver::Drive::cycle, autd3::driver::Drive::phase, and autd3::driver::rem_euclid().
Referenced by set().
Member Data Documentation
phase
uint16_t autd3::driver::Phase::phase
Definition at line 101 of file defined.hpp.
Referenced by set().
The documentation for this struct was generated from the following file:
include/autd3/driver/fpga/defined.hpp