autd3: autd3::core::DynamicTransducer Struct Reference
autd3::core::DynamicTransducer Struct Reference final
Transduce with variable frequency.
#include <dynamic_transducer.hpp>
Public Member Functions
DynamicTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
~DynamicTransducer () override=default
DynamicTransducer (const DynamicTransducer &v) noexcept=default
DynamicTransducer & operator= (const DynamicTransducer &obj)=default
DynamicTransducer (DynamicTransducer &&obj)=default
DynamicTransducer & operator= (DynamicTransducer &&obj)=default
uint16_t cycle () const noexcept override
double frequency () const noexcept override
double wavelength (const double sound_speed) const noexcept override
Wavelength of the ultrasound emitted from the transducer.
double wavenumber (const double sound_speed) const noexcept override
Wavenumber of the ultrasound emitted from the transducer.
void set_cycle (const uint16_t cycle) noexcept
void set_frequency (const double freq) noexcept
Public Member Functions inherited from autd3::core::Transducer< DynamicDriveData< DynamicTransducer > >
Transducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
Transducer (const Transducer &v) noexcept=default
Transducer (Transducer &&obj)=default
virtual ~Transducer ()=default
Transducer & operator= (const Transducer &obj)=default
Transducer & operator= (Transducer &&obj)=default
double align_phase_at (const double dist, const double sound_speed) const
const Vector3 & position () const noexcept
Position of the transducer.
size_t id () const noexcept
ID of the transducer.
const Vector3 & x_direction () const noexcept
x direction of the transducer
const Vector3 & y_direction () const noexcept
y direction of the transducer
const Vector3 & z_direction () const noexcept
z direction of the transducer
uint16_t mod_delay () const noexcept
modulation delay of the transducer
uint16_t & mod_delay () noexcept
modulation delay of the transducer
virtual uint16_t cycle () const=0
Frequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
virtual double frequency () const=0
Frequency of the transducer.
Static Public Member Functions
static void pack_header (driver::TxDatagram &tx) noexcept
static void pack_body (bool &phase_sent, bool &duty_sent, const D &drives, driver::TxDatagram &tx) noexcept
static TransducerMode & mode ()
Additional Inherited Members
Public Types inherited from autd3::core::Transducer< DynamicDriveData< DynamicTransducer > >
using D = DynamicDriveData< DynamicTransducer >
Detailed Description
Transduce with variable frequency.
Definition at line 77 of file dynamic_transducer.hpp.
Constructor & Destructor Documentation
DynamicTransducer() [1/3]
autd3::core::DynamicTransducer::DynamicTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) inline noexcept
Definition at line 78 of file dynamic_transducer.hpp.
~DynamicTransducer()
autd3::core::DynamicTransducer::~DynamicTransducer () override default
DynamicTransducer() [2/3]
autd3::core::DynamicTransducer::DynamicTransducer (const DynamicTransducer & v) default noexcept
DynamicTransducer() [3/3]
autd3::core::DynamicTransducer::DynamicTransducer (DynamicTransducer && obj) default
Member Function Documentation
cycle()
uint16_t autd3::core::DynamicTransducer::cycle () const inline override noexcept
Definition at line 86 of file dynamic_transducer.hpp.
Referenced by set_cycle(), and set_frequency().
frequency()
double autd3::core::DynamicTransducer::frequency () const inline override noexcept
Definition at line 87 of file dynamic_transducer.hpp.
References autd3::driver::FPGA_CLK_FREQ.
Referenced by wavelength(), and wavenumber().
mode()
static TransducerMode& autd3::core::DynamicTransducer::mode () inline static
Definition at line 153 of file dynamic_transducer.hpp.
Referenced by autd3::core::GainSTM< DynamicTransducer >::is_finished(), autd3::core::GainSTM< DynamicTransducer >::pack(), and autd3::ControllerX< T, >::stop().
operator=() [1/2]
DynamicTransducer& autd3::core::DynamicTransducer::operator= (const DynamicTransducer & obj) default
operator=() [2/2]
DynamicTransducer& autd3::core::DynamicTransducer::operator= (DynamicTransducer && obj) default
pack_body()
static void autd3::core::DynamicTransducer::pack_body (bool & phase_sent, bool & duty_sent, const D & drives, driver::TxDatagram & tx) inline static noexcept
Definition at line 106 of file dynamic_transducer.hpp.
References autd3::core::Legacy, autd3::core::Normal, autd3::driver::normal_duty_body(), autd3::driver::normal_legacy_body(), autd3::driver::normal_phase_body(), and autd3::core::NormalPhase.
pack_header()
static void autd3::core::DynamicTransducer::pack_header (driver::TxDatagram & tx) inline static noexcept
Definition at line 91 of file dynamic_transducer.hpp.
References autd3::core::Legacy, autd3::core::Normal, autd3::driver::normal_header(), autd3::driver::normal_legacy_header(), and autd3::core::NormalPhase.
set_cycle()
void autd3::core::DynamicTransducer::set_cycle (const uint16_t cycle) inline noexcept
Definition at line 136 of file dynamic_transducer.hpp.
References cycle(), autd3::core::Legacy, autd3::core::Normal, and autd3::core::NormalPhase.
Referenced by set_frequency().
set_frequency()
void autd3::core::DynamicTransducer::set_frequency (const double freq) inline noexcept
Definition at line 148 of file dynamic_transducer.hpp.
References cycle(), autd3::driver::FPGA_CLK_FREQ, and set_cycle().
wavelength()
double autd3::core::DynamicTransducer::wavelength (const double sound_speed) const inline override virtual noexcept
Wavelength of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< DynamicDriveData< DynamicTransducer > >.
Definition at line 88 of file dynamic_transducer.hpp.
References frequency().
wavenumber()
double autd3::core::DynamicTransducer::wavenumber (const double sound_speed) const inline override virtual noexcept
Wavenumber of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< DynamicDriveData< DynamicTransducer > >.
Definition at line 89 of file dynamic_transducer.hpp.
References frequency(), and autd3::driver::pi.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/dynamic_transducer.hpp