autd3: autd3::core::Device< T > Struct Template Reference
autd3::core::Device< T > Struct Template Reference
Device contains an AUTD device geometry.
#include <device.hpp>
Public Member Functions
Device (const size_t id, const Vector3 &position, const Quaternion &rotation)
Device ()=delete
~Device ()=default
Device (const Device &v) noexcept=default
Device & operator= (const Device &obj)=default
Device (Device &&obj)=default
Device & operator= (Device &&obj)=default
Vector3 center () const
Center position of this device.
Vector3 to_local_position (const Vector3 &global_position) const
Convert a global position to a local position.
std::vector< T >::const_iterator begin () const noexcept
std::vector< T >::const_iterator end () const noexcept
std::vector< T >::iterator begin () noexcept
std::vector< T >::iterator end () noexcept
const T & operator[] (const size_t i) const
T & operator[] (const size_t i)
Detailed Description
template<typename T>
struct autd3::core::Device< T >
Device contains an AUTD device geometry.
Definition at line 25 of file device.hpp.
Constructor & Destructor Documentation
Device() [1/4]
template<typename T > autd3::core::Device< T >::Device (const size_t id, const Vector3 & position, const Quaternion & rotation) inline explicit
Definition at line 26 of file device.hpp.
Device() [2/4]
template<typename T > autd3::core::Device< T >::Device () delete
~Device()
template<typename T > autd3::core::Device< T >::~Device () default
Device() [3/4]
template<typename T > autd3::core::Device< T >::Device (const Device< T > & v) default noexcept
Device() [4/4]
template<typename T > autd3::core::Device< T >::Device (Device< T > && obj) default
Member Function Documentation
begin() [1/2]
template<typename T > std::vector<T>::const_iterator autd3::core::Device< T >::begin () const inline noexcept
Definition at line 74 of file device.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::center().
begin() [2/2]
template<typename T > std::vector<T>::iterator autd3::core::Device< T >::begin () inline noexcept
Definition at line 76 of file device.hpp.
center()
template<typename T > Vector3 autd3::core::Device< T >::center () const inline
Center position of this device.
Definition at line 55 of file device.hpp.
Referenced by autd3::core::Geometry< autd3::core::LegacyTransducer >::center().
end() [1/2]
template<typename T > std::vector<T>::const_iterator autd3::core::Device< T >::end () const inline noexcept
Definition at line 75 of file device.hpp.
Referenced by autd3::core::Device< autd3::core::LegacyTransducer >::center().
end() [2/2]
template<typename T > std::vector<T>::iterator autd3::core::Device< T >::end () inline noexcept
Definition at line 77 of file device.hpp.
operator=() [1/2]
template<typename T > Device& autd3::core::Device< T >::operator= (const Device< T > & obj) default
operator=() [2/2]
template<typename T > Device& autd3::core::Device< T >::operator= (Device< T > && obj) default
operator[]() [1/2]
template<typename T > T& autd3::core::Device< T >::operator[] (const size_t i) inline
Definition at line 80 of file device.hpp.
operator[]() [2/2]
template<typename T > const T& autd3::core::Device< T >::operator[] (const size_t i) const inline
Definition at line 79 of file device.hpp.
to_local_position()
template<typename T > Vector3 autd3::core::Device< T >::to_local_position (const Vector3 & global_position) const inline
Convert a global position to a local position.
Definition at line 68 of file device.hpp.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/device.hpp