autd3: autd3::core::ModDelayConfig< T, > Struct Template Reference
autd3::core::ModDelayConfig< T, > Struct Template Reference final
Gain controls the duty ratio and phase of each transducer in AUTD devices.
#include <delay.hpp>
Public Member Functions
ModDelayConfig ()
~ModDelayConfig () override=default
ModDelayConfig (const ModDelayConfig &v)=default
ModDelayConfig & operator= (const ModDelayConfig &obj)=default
ModDelayConfig (ModDelayConfig &&obj)=default
ModDelayConfig & operator= (ModDelayConfig &&obj)=default
void init () override
void pack (const Geometry< T > &geometry, driver::TxDatagram &tx) override
bool is_finished () const noexcept override
Public Member Functions inherited from autd3::core::DatagramBody< autd3::core::LegacyTransducer >
DatagramBody ()=default
DatagramBody (const DatagramBody &v)=default
DatagramBody (DatagramBody &&obj)=default
virtual ~DatagramBody ()=default
DatagramBody & operator= (const DatagramBody &obj)=default
DatagramBody & operator= (DatagramBody &&obj)=default
virtual void pack (const Geometry< autd3::core::LegacyTransducer > &geometry, driver::TxDatagram &tx)=0
virtual bool is_finished () const=0
Detailed Description
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr>
struct autd3::core::ModDelayConfig< T, >
Gain controls the duty ratio and phase of each transducer in AUTD devices.
Definition at line 28 of file delay.hpp.
Constructor & Destructor Documentation
ModDelayConfig() [1/3]
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::ModDelayConfig< T, >::ModDelayConfig () inline
Definition at line 29 of file delay.hpp.
~ModDelayConfig()
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::ModDelayConfig< T, >::~ModDelayConfig () override default
ModDelayConfig() [2/3]
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::ModDelayConfig< T, >::ModDelayConfig (const ModDelayConfig< T, > & v) default
ModDelayConfig() [3/3]
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> autd3::core::ModDelayConfig< T, >::ModDelayConfig (ModDelayConfig< T, > && obj) default
Member Function Documentation
init()
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::ModDelayConfig< T, >::init () inline override virtual
Implements autd3::core::DatagramBody< autd3::core::LegacyTransducer >.
Definition at line 36 of file delay.hpp.
is_finished()
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> bool autd3::core::ModDelayConfig< T, >::is_finished () const inline override noexcept
Definition at line 52 of file delay.hpp.
Referenced by autd3::core::ModDelayConfig< T, >::pack().
operator=() [1/2]
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> ModDelayConfig& autd3::core::ModDelayConfig< T, >::operator= (const ModDelayConfig< T, > & obj) default
operator=() [2/2]
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> ModDelayConfig& autd3::core::ModDelayConfig< T, >::operator= (ModDelayConfig< T, > && obj) default
pack()
template<typename T = autd3::core::LegacyTransducer, std::enable_if_t< std::is_base_of_v< Transducer< typename T::D >, T >, nullptr_t > = nullptr> void autd3::core::ModDelayConfig< T, >::pack (const Geometry< T > & geometry, driver::TxDatagram & tx) inline override
Definition at line 38 of file delay.hpp.
References autd3::core::Geometry< T, >::begin(), autd3::core::Geometry< T, >::end(), autd3::core::ModDelayConfig< T, >::is_finished(), and autd3::driver::null_body().
The documentation for this struct was generated from the following file:
include/autd3/core/delay.hpp