autd3: autd3::driver::FPGAInfo Struct Reference
autd3::driver::FPGAInfo Struct Reference
#include <defined.hpp>
Public Member Functions
FPGAInfo () noexcept
FPGAInfo (const uint8_t ack) noexcept
bool is_thermal_assert () const noexcept
std::string to_string () const
Public Attributes
uint8_t info
Detailed Description
Definition at line 108 of file defined.hpp.
Constructor & Destructor Documentation
FPGAInfo() [1/2]
autd3::driver::FPGAInfo::FPGAInfo () inline noexcept
Definition at line 111 of file defined.hpp.
FPGAInfo() [2/2]
autd3::driver::FPGAInfo::FPGAInfo (const uint8_t ack) inline explicit noexcept
Definition at line 112 of file defined.hpp.
Member Function Documentation
is_thermal_assert()
bool autd3::driver::FPGAInfo::is_thermal_assert () const inline noexcept
Definition at line 114 of file defined.hpp.
References info.
Referenced by to_string().
to_string()
std::string autd3::driver::FPGAInfo::to_string () const inline
Definition at line 116 of file defined.hpp.
References is_thermal_assert().
Referenced by autd3::driver::operator<<().
Member Data Documentation
info
uint8_t autd3::driver::FPGAInfo::info
Definition at line 109 of file defined.hpp.
Referenced by is_thermal_assert().
The documentation for this struct was generated from the following file:
include/autd3/driver/fpga/defined.hpp