autd3: autd3::core::NormalPhaseTransducer Struct Reference
autd3::core::NormalPhaseTransducer Struct Reference final
Transduce with variable frequency (phase only)
#include <normal_phase_transducer.hpp>
Public Member Functions
NormalPhaseTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
~NormalPhaseTransducer () override=default
NormalPhaseTransducer (const NormalPhaseTransducer &v) noexcept=default
NormalPhaseTransducer & operator= (const NormalPhaseTransducer &obj)=default
NormalPhaseTransducer (NormalPhaseTransducer &&obj)=default
NormalPhaseTransducer & operator= (NormalPhaseTransducer &&obj)=default
uint16_t cycle () const noexcept override
double frequency () const noexcept override
double wavelength (const double sound_speed) const noexcept override
Wavelength of the ultrasound emitted from the transducer.
double wavenumber (const double sound_speed) const noexcept override
Wavenumber of the ultrasound emitted from the transducer.
void set_cycle (const uint16_t cycle) noexcept
void set_frequency (const double freq) noexcept
Public Member Functions inherited from autd3::core::Transducer< NormalPhaseDriveData< NormalPhaseTransducer > >
Transducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) noexcept
Transducer (const Transducer &v) noexcept=default
Transducer (Transducer &&obj)=default
virtual ~Transducer ()=default
Transducer & operator= (const Transducer &obj)=default
Transducer & operator= (Transducer &&obj)=default
double align_phase_at (const double dist, const double sound_speed) const
const Vector3 & position () const noexcept
Position of the transducer.
size_t id () const noexcept
ID of the transducer.
const Vector3 & x_direction () const noexcept
x direction of the transducer
const Vector3 & y_direction () const noexcept
y direction of the transducer
const Vector3 & z_direction () const noexcept
z direction of the transducer
uint16_t mod_delay () const noexcept
modulation delay of the transducer
uint16_t & mod_delay () noexcept
modulation delay of the transducer
virtual uint16_t cycle () const=0
Frequency division ratio. The frequency will be autd3::driver::FPGA_CLK_FREQ/cycle.
virtual double frequency () const=0
Frequency of the transducer.
Static Public Member Functions
static void pack_header (driver::TxDatagram &tx) noexcept
static void pack_body (bool &phase_sent, bool &duty_sent, const D &drives, driver::TxDatagram &tx) noexcept
Additional Inherited Members
Public Types inherited from autd3::core::Transducer< NormalPhaseDriveData< NormalPhaseTransducer > >
using D = NormalPhaseDriveData< NormalPhaseTransducer >
Detailed Description
Transduce with variable frequency (phase only)
Definition at line 45 of file normal_phase_transducer.hpp.
Constructor & Destructor Documentation
NormalPhaseTransducer() [1/3]
autd3::core::NormalPhaseTransducer::NormalPhaseTransducer (const size_t id, Vector3 pos, Vector3 x_direction, Vector3 y_direction, Vector3 z_direction) inline noexcept
Definition at line 46 of file normal_phase_transducer.hpp.
~NormalPhaseTransducer()
autd3::core::NormalPhaseTransducer::~NormalPhaseTransducer () override default
NormalPhaseTransducer() [2/3]
autd3::core::NormalPhaseTransducer::NormalPhaseTransducer (const NormalPhaseTransducer & v) default noexcept
NormalPhaseTransducer() [3/3]
autd3::core::NormalPhaseTransducer::NormalPhaseTransducer (NormalPhaseTransducer && obj) default
Member Function Documentation
cycle()
uint16_t autd3::core::NormalPhaseTransducer::cycle () const inline override noexcept
Definition at line 54 of file normal_phase_transducer.hpp.
Referenced by set_cycle(), and set_frequency().
frequency()
double autd3::core::NormalPhaseTransducer::frequency () const inline override noexcept
Definition at line 55 of file normal_phase_transducer.hpp.
References autd3::driver::FPGA_CLK_FREQ.
Referenced by wavelength(), and wavenumber().
operator=() [1/2]
NormalPhaseTransducer& autd3::core::NormalPhaseTransducer::operator= (const NormalPhaseTransducer & obj) default
operator=() [2/2]
NormalPhaseTransducer& autd3::core::NormalPhaseTransducer::operator= (NormalPhaseTransducer && obj) default
pack_body()
static void autd3::core::NormalPhaseTransducer::pack_body (bool & phase_sent, bool & duty_sent, const D & drives, driver::TxDatagram & tx) inline static noexcept
Definition at line 61 of file normal_phase_transducer.hpp.
References autd3::driver::normal_phase_body().
pack_header()
static void autd3::core::NormalPhaseTransducer::pack_header (driver::TxDatagram & tx) inline static noexcept
Definition at line 59 of file normal_phase_transducer.hpp.
References autd3::driver::normal_header().
set_cycle()
void autd3::core::NormalPhaseTransducer::set_cycle (const uint16_t cycle) inline noexcept
Definition at line 67 of file normal_phase_transducer.hpp.
References cycle().
Referenced by set_frequency().
set_frequency()
void autd3::core::NormalPhaseTransducer::set_frequency (const double freq) inline noexcept
Definition at line 69 of file normal_phase_transducer.hpp.
References cycle(), autd3::driver::FPGA_CLK_FREQ, and set_cycle().
wavelength()
double autd3::core::NormalPhaseTransducer::wavelength (const double sound_speed) const inline override virtual noexcept
Wavelength of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< NormalPhaseDriveData< NormalPhaseTransducer > >.
Definition at line 56 of file normal_phase_transducer.hpp.
References frequency().
wavenumber()
double autd3::core::NormalPhaseTransducer::wavenumber (const double sound_speed) const inline override virtual noexcept
Wavenumber of the ultrasound emitted from the transducer.
Parameters
sound_speed Speed of sound in m/s.
Implements autd3::core::Transducer< NormalPhaseDriveData< NormalPhaseTransducer > >.
Definition at line 57 of file normal_phase_transducer.hpp.
References frequency(), and autd3::driver::pi.
The documentation for this struct was generated from the following file:
include/autd3/core/geometry/normal_phase_transducer.hpp